import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { VehicleGroupsComponent, VehicleGroup } from '../vehiclegroups/vehiclegroups.component';
import { FormGroup, FormControl } from '@angular/forms';
import { PricingService } from './pricing.service';
import { startWith, map } from 'rxjs/operators';
import { Price } from './price';
import { CustomerService } from '../customer/customer.service'
import { AuthService } from '../../../core/auth.service';
import { User } from '../../../core/user';
import { Customer } from '../customer';
import { MatSnackBar, MatDialog } from '@angular/material';
import { SubUser } from '../sub-users/sub-user';
import { async } from 'q';
import { CustomerselectionComponent } from '../customerselection/customerselection.component';

@Component({
  selector: 'app-pricing',
  templateUrl: './pricing.component.html',
  styleUrls: ['./pricing.component.scss']
})
export class PricingComponent implements OnInit {

  myform:FormGroup;
  priceArray:any[];
  customers:Customer[];
  customer:any;
  customerCtrl:FormControl=new FormControl();
  filteredOptions: Observable<string[]>;
  cityCtrl: FormControl = new FormControl();
  user:User={}
  toggleSupplier=false;
  permission:SubUser={};
  city=[];
  customerCopyName=''
  
  constructor(
    private priceService:PricingService,
    private vehicleGroups:VehicleGroupsComponent,
    private auth:AuthService,
    private snackBar:MatSnackBar,
    private customerService: CustomerService,
    private dialog:MatDialog
  ) { }

  keyPress(event: any) {
    const charCode = (event.which) ? event.which : event.keyCode;
    if (charCode > 31 && (charCode < 48 || charCode > 57)) {
      return false;
    }
    return true;
  }

  selectVehicle(temp:any,event:any)
  {
    if(event.source.selected==true)
    {
      this.temp.vehicleGroupId=temp.id;
      this.price.vehicleGroupId=temp.id;
      this.priceService.getPrices(this.temp).subscribe(res=>this.priceArray=res);
    }
  }
  selectCity(temp:any,event:any)
  {
    if(event.source.selected==true)
    {
      this.temp.city=temp;
      this.price.city=temp;
      this.priceService.getPrices(this.temp).subscribe(res=>this.priceArray=res);
    }
  }

  selectCustomer(temp:any,event:any)
  {
    if(event.source.selected==true)
    {
      if(temp.customerOwnerId!=null)
      {
        this.toggleSupplier = true
      }
      else
      {
        this.toggleSupplier = false
      }
      this.temp.customerId=temp.id;
      this.customerCopyName=temp.name;
      this.price.customerId=temp.id;
      this.priceService.getPrices(this.temp).subscribe(res=>this.priceArray=res);
      this.customerService.getCustomerLimitVehicleGroupForBookings(temp).toPromise().then(data => {
        if(data.length != 0) {
          this.temp.vehicleGroupId=data[0].id
          this.price.vehicleGroupId=data[0].id
          this.vehicleGroupCtrl.setValue(data[0].name)
          this.vehicleGroup=data;
          this.vehicleGroup0=this.vehicleGroupCtrl.valueChanges
          .pipe(
            startWith(''),
            map(val=>this.filterVehicleGroup(val))
          );
        }
        else {
          this.getVehicleGroups();
        }
      })

      this.customerService.getCustomerLimitCity(temp).subscribe(data => {
        if(data.length != 0) {
          this.city.length = 0;
          data.forEach(element => {
            this.city.push(element.city);
          });          
        }
        else {
          this.getCities();          
        }
        
      },err=>{},()=>{
        this.filterCities();
      })
    }
  }

  ngOnInit() {

    this.auth.user.subscribe(async data=>{
      this.user=data[0]
      this.auth.permissions.subscribe(data => {
        this.permission=data[0];
        if(this.permission.managePricing === 0) {
          this.snackBar.open('You do not have permission to edit pricing',"X",{verticalPosition:'top',horizontalPosition:'right'});
        }
      })
      this.temp.ownerId=this.user.ownerId;
      // this.temp.city='Mumbai'
      // this.price.city='Mumbai'
      // this.cityCtrl.setValue('Mumbai')

      await this.priceService.getCustomers(this.user).toPromise().then(data=>{
        this.temp.customerId=data[0].id
        this.price.customerId=data[0].id
        this.customerCtrl.setValue(data[0].name)
        this.customers=data
        this.customer=this.customerCtrl.valueChanges
        .pipe(
          startWith(''),
          map(val=>this.filterCustomer(val))
        );
        this.customerService.getCustomerLimitVehicleGroupForBookings(data[0]).toPromise().then(data => {
          if(data.length != 0) {
            this.temp.vehicleGroupId=data[0].id
            this.price.vehicleGroupId=data[0].id
            this.vehicleGroupCtrl.setValue(data[0].name)
            this.vehicleGroup=data;
            this.vehicleGroup0=this.vehicleGroupCtrl.valueChanges
            .pipe(
              startWith(''),
              map(val=>this.filterVehicleGroup(val))
            );

          this.priceService.getPrices(this.temp).subscribe(res=>this.priceArray=res);
          }
          else {
            this.getVehicleGroups();            
          }
        })
        this.customerService.getCustomerLimitCity(data[0]).subscribe(data => {
          if(data.length != 0) {
            this.city.length = 0;
            data.forEach(element => {
              this.city.push(element.city);
            });          
            this.temp.city=data[0]
            this.price.city=data[0]
            this.cityCtrl.setValue(data[0])
          }
          else {
            this.getCities();          
          }
          
        },err=>{},()=>{
          this.filterCities();
        })
      })
      // this.priceService.getPrices(this.temp).subscribe(res=>this.priceArray=res);
    });
    // this.filteredOptions = this.cityCtrl.valueChanges
    //   .pipe(
    //     startWith(''),
    //     map(val => this.filter(val))
    //   );
  }
  

  getVehicleGroups() {
    this.vehicleGroups.getvehicleGroup(this.user).toPromise().then(data=>{
      this.temp.vehicleGroupId=data[0].id
      this.price.vehicleGroupId=data[0].id
      this.vehicleGroupCtrl.setValue(data[0].name)
      this.vehicleGroup=data;
      this.vehicleGroup0=this.vehicleGroupCtrl.valueChanges
        .pipe(
          startWith(''),
          map(val=>this.filterVehicleGroup(val))
        );

        this.priceService.getPrices(this.temp).subscribe(res=>this.priceArray=res);
    });
  }

  getCities() {
    this.city=[
      'All',
      'Ahmedabad',
      'Mumbai',
      'Hyderabad',
      'Chennai',
      'Kolkata',
      'Pune',
      'Jaipur',
      'Surat',
      'Lucknow',
      'Kanpur',
      'Nagpur',
      'Patna',
      'Indore',
      'Thane',
      'Bhopal',
      'Visakhapatnam',
      'Vadodara',
      'Firozabad',
      'Ludhiana',
      'Rajkot',
      'Agra',
      'Siliguri',
      'Nashik',
      'Faridabad',
      'Patiala',
      'Meerut',
      'Kalyan-Dombivali',
      'Vasai-Virar',
      'Varanasi',
      'Srinagar',
      'Dhanbad',
      'Jodhpur',
      'Amritsar',
      'Raipur',
      'Allahabad',
      'Coimbatore',
      'Jabalpur',
      'Gwalior',
      'Vijayawada',
      'Madurai',
      'Guwahati',
      'Chandigarh',
      'Hubli-Dharwad',
      'Amroha',
      'Moradabad',
      'Gurgaon',
      'Aligarh',
      'Solapur',
      'Ranchi',
      'Jalandhar',
      'Tiruchirappalli',
      'Bhubaneswar',
      'Salem',
      'Warangal',
      'Mira-Bhayandar',
      'Thiruvananthapuram',
      'Bhiwandi',
      'Saharanpur',
      'Guntur',
      'Amravati',
      'Bikaner',
      'Noida',
      'Jamshedpur',
      'Bhilai Nagar',
      'Cuttack',
      'Kochi',
      'Udaipur',
      'Bhavnagar',
      'Dehradun',
      'Asansol',
      'Nanded-Waghala',
      'Ajmer',
      'Jamnagar',
      'Ujjain',
      'Sangli',
      'Loni',
      'Jhansi',
      'Pondicherry',
      'Nellore',
      'Jammu',
      'Belagavi',
      'Raurkela',
      'Mangaluru',
      'Tirunelveli',
      'Malegaon',
      'Gaya',
      'Tiruppur',
      'Davanagere',
      'Kozhikode',
      'Akola',
      'Kurnool',
      'Bokaro Steel City',
      'Rajahmundry',
      'Ballari',
      'Agartala',
      'Bhagalpur',
      'Latur',
      'Dhule',
      'Korba',
      'Bhilwara',
      'Brahmapur',
      'Mysore',
      'Muzaffarpur',
      'Ahmednagar',
      'Kollam',
      'Raghunathganj',
      'Bilaspur',
      'Shahjahanpur',
      'Thrissur',
      'Alwar',
      'Kakinada',
      'Nizamabad',
      'Sagar',
      'Tumkur',
      'Hisar',
      'Rohtak',
      'Panipat',
      'Darbhanga',
      'Kharagpur',
      'Aizawl',
      'Ichalkaranji',
      'Tirupati',
      'Karnal',
      'Bathinda',
      'Rampur',
      'Shivamogga',
      'Ratlam',
      'Modinagar',
      'Durg',
      'Shillong',
      'Imphal',
      'Hapur',
      'Ranipet',
      'Anantapur',
      'Arrah',
      'Karimnagar',
      'Parbhani',
      'Etawah',
      'Bharatpur',
      'Begusarai',
      'New Delhi',
      'Chhapra',
      'Kadapa',
      'Ramagundam',
      'Pali',
      'Satna',
      'Vizianagaram',
      'Katihar',
      'Hardwar',
      'Sonipat',
      'Nagercoil',
      'Thanjavur',
      'Murwara (Katni)',
      'Naihati',
      'Sambhal',
      'Nadiad',
      'Yamunanagar',
      'English Bazar',
      'Eluru',
      'Munger',
      'Panchkula',
      'Raayachuru',
      'Panvel',
      'Deoghar',
      'Ongole',
      'Nandyal',
      'Morena',
      'Bhiwani',
      'Porbandar',
      'Palakkad',
      'Anand',
      'Purnia',
      'Baharampur',
      'Barmer',
      'Morvi',
      'Orai',
      'Bahraich',
      'Sikar',
      'Vellore',
      'Singrauli',
      'Khammam',
      'Mahesana',
      'Silchar',
      'Sambalpur',
      'Rewa',
      'Unnao',
      'Hugli-Chinsurah',
      'Raiganj',
      'Phusro',
      'Adityapur',
      'Alappuzha',
      'Bahadurgarh',
      'Machilipatnam',
      'Rae Bareli',
      'Jalpaiguri',
      'Bharuch',
      'Pathankot',
      'Hoshiarpur',
      'Baramula',
      'Adoni',
      'Jind',
      'Tonk',
      'Tenali',
      'Kancheepuram',
      'Vapi',
      'Sirsa',
      'Navsari',
      'Mahbubnagar',
      'Puri',
      'Robertson Pet',
      'Erode',
      'Batala',
      'Haldwani-cum-Kathgodam',
      'Vidisha',
      'Saharsa',
      'Thanesar',
      'Chittoor',
      'Veraval',
      'Lakhimpur',
      'Sitapur',
      'Hindupur',
      'Santipur',
      'Balurghat',
      'Ganjbasoda',
      'Moga',
      'Proddatur',
      'Srinagar',
      'Medinipur',
      'Habra',
      'Sasaram',
      'Hajipur',
      'Bhuj',
      'Shivpuri',
      'Ranaghat',
      'Shimla',
      'Tiruvannamalai',
      'Kaithal',
      'Rajnandgaon',
      'Godhra',
      'Hazaribag',
      'Bhimavaram',
      'Mandsaur',
      'Dibrugarh',
      'Kolar',
      'Bankura',
      'Mandya',
      'Dehri-on-Sone',
      'Madanapalle',
      'Malerkotla',
      'Lalitpur',
      'Bettiah',
      'Pollachi',
      'Khanna',
      'Neemuch',
      'Palwal',
      'Palanpur',
      'Guntakal',
      'Nabadwip',
      'Udupi',
      'Jagdalpur',
      'Motihari',
      'Pilibhit',
      'Dimapur',
      'Mohali',
      'Sadulpur',
      'Rajapalayam',
      'Dharmavaram',
      'Kashipur',
      'Sivakasi',
      'Darjiling',
      'Chikkamagaluru',
      'Gudivada',
      'Baleshwar Town',
      'Mancherial',
      'Srikakulam',
      'Adilabad',
      'Yavatmal',
      'Barnala',
      'Nagaon',
      'Narasaraopet',
      'Raigarh',
      'Roorkee',
      'Valsad',
      'Ambikapur',
      'Giridih',
      'Chandausi',
      'Purulia',
      'Patan',
      'Bagaha',
      'Hardoi ',
      'Achalpur',
      'Osmanabad',
      'Deesa',
      'Nandurbar',
      'Azamgarh',
      'Ramgarh',
      'Firozpur',
      'Baripada Town',
      'Karwar',
      'Siwan',
      'Rajampet',
      'Pudukkottai',
      'Anantnag',
      'Tadpatri',
      'Satara',
      'Bhadrak',
      'Kishanganj',
      'Suryapet',
      'Wardha',
      'Ranebennuru',
      'Amreli',
      'Neyveli (TS)',
      'Jamalpur',
      'Marmagao',
      'Udgir',
      'Tadepalligudem',
      'Nagapattinam',
      'Buxar',
      'Aurangabad',
      'Jehanabad',
      'Phagwara',
      'Khair',
      'Sawai Madhopur',
      'Kapurthala',
      'Chilakaluripet',
      'Aurangabad',
      'Malappuram',
      'Rewari',
      'Nagaur',
      'Sultanpur',
      'Nagda',
      'Port Blair',
      'Lakhisarai',
      'Panaji',
      'Tinsukia',
      'Itarsi',
      'Kohima',
      'Balangir',
      'Nawada',
      'Jharsuguda',
      'Jagtial',
      'Viluppuram',
      'Amalner',
      'Zirakpur',
      'Tanda',
      'Tiruchengode',
      'Nagina',
      'Yemmiganur',
      'Vaniyambadi',
      'Sarni',
      'Theni Allinagaram',
      'Margao',
      'Akot',
      'Sehore',
      'Mhow Cantonment',
      'Kot Kapura',
      'Makrana',
      'Pandharpur',
      'Miryalaguda',
      'Shamli',
      'Seoni',
      'Ranibennur',
      'Kadiri',
      'Shrirampur',
      'Rudrapur',
      'Parli',
      'Najibabad',
      'Nirmal',
      'Udhagamandalam',
      'Shikohabad',
      'Jhumri Tilaiya',
      'Aruppukkottai',
      'Ponnani',
      'Jamui',
      'Sitamarhi',
      'Chirala',
      'Anjar',
      'Karaikal',
      'Hansi',
      'Anakapalle',
      'Mahasamund',
      'Faridkot',
      'Saunda',
      'Dhoraji',
      'Paramakudi',
      'Balaghat',
      'Sujangarh',
      'Khambhat',
      'Muktsar',
      'Rajpura',
      'Kavali',
      'Dhamtari',
      'Ashok Nagar',
      'Sardarshahar',
      'Mahuva',
      'Bargarh',
      'Kamareddy',
      'Sahibganj',
      'Kothagudem',
      'Ramanagaram',
      'Gokak',
      'Tikamgarh',
      'Araria',
      'Rishikesh',
      'Shahdol',
      'Medininagar (Daltonganj)',
      'Arakkonam',
      'Washim',
      'Sangrur',
      'Bodhan',
      'Fazilka',
      'Palacole',
      'Keshod',
      'Sullurpeta',
      'Wadhwan',
      'Gurdaspur',
      'Vatakara',
      'Tura',
      'Narnaul',
      'Kharar',
      'Yadgir',
      'Ambejogai',
      'Ankleshwar',
      'Savarkundla',
      'Paradip',
      'Virudhachalam',
      'Kanhangad',
      'Kadi',
      'Srivilliputhur',
      'Gobindgarh',
      'Tindivanam',
      'Mansa',
      'Taliparamba',
      'Manmad',
      'Tanuku',
      'Rayachoti',
      'Virudhunagar',
      'Koyilandy',
      'Jorhat',
      'Karur',
      'Valparai',
      'Srikalahasti',
      'Neyyattinkara',
      'Bapatla',
      'Fatehabad',
      'Malout',
      'Sankarankovil',
      'Tenkasi',
      'Ratnagiri',
      'Rabkavi Banhatti',
      'Sikandrabad',
      'Chaibasa',
      'Chirmiri',
      'Palwancha',
      'Bhawanipatna',
      'Kayamkulam',
      'Pithampur',
      'Nabha',
      'Shahabad, Hardoi',
      'Dhenkanal',
      'Uran Islampur',
      'Gopalganj',
      'Bongaigaon City',
      'Palani',
      'Pusad',
      'Sopore',
      'Pilkhuwa',
      'Tarn Taran',
      'Renukoot',
      'Mandamarri',
      'Shahabad',
      'Barbil',
      'Koratla',
      'Madhubani',
      'Arambagh',
      'Gohana',
      'Ladnu',
      'Pattukkottai',
      'Sirsi',
      'Sircilla',
      'Tamluk',
      'Jagraon',
      'AlipurdUrban Agglomerationr',
      'Alirajpur',
      'Tandur',
      'Naidupet',
      'Tirupathur',
      'Tohana',
      'Ratangarh',
      'Dhubri',
      'Masaurhi',
      'Visnagar',
      'Vrindavan',
      'Nokha',
      'Nagari',
      'Narwana',
      'Ramanathapuram',
      'Ujhani',
      'Samastipur',
      'Laharpur',
      'Sangamner',
      'Nimbahera',
      'Siddipet',
      'Suri',
      'Diphu',
      'Jhargram',
      'Shirpur-Warwade',
      'Tilhar',
      'Sindhnur',
      'Udumalaipettai',
      'Malkapur',
      'Wanaparthy',
      'Gudur',
      'Kendujhar',
      'Mandla',
      'Mandi',
      'Nedumangad',
      'North Lakhimpur',
      'Vinukonda',
      'Tiptur',
      'Gobichettipalayam',
      'Sunabeda',
      'Wani',
      'Upleta',
      'Narasapuram',
      'Nuzvid',
      'Tezpur',
      'Una',
      'Markapur',
      'Sheopur',
      'Thiruvarur',
      'Sidhpur',
      'Sahaswan',
      'Suratgarh',
      'Shajapur',
      'Rayagada',
      'Lonavla',
      'Ponnur',
      'Kagaznagar',
      'Gadwal',
      'Bhatapara',
      'Kandukur',
      'Sangareddy',
      'Unjha',
      'Lunglei',
      'Karimganj',
      'Kannur',
      'Bobbili',
      'Mokameh',
      'Talegaon Dabhade',
      'Anjangaon',
      'Mangrol',
      'Sunam',
      'Gangarampur',
      'Thiruvallur',
      'Tirur',
      'Rath',
      'Jatani',
      'Viramgam',
      'Rajsamand',
      'Yanam',
      'Kottayam',
      'Panruti',
      'Dhuri',
      'Namakkal',
      'Kasaragod',
      'Modasa',
      'Rayadurg',
      'Supaul',
      'Kunnamkulam',
      'Umred',
      'Bellampalle',
      'Sibsagar',
      'Mandi Dabwali',
      'Ottappalam',
      'Dumraon',
      'Samalkot',
      'Jaggaiahpet',
      'Goalpara',
      'Tuni',
      'Lachhmangarh',
      'Bhongir',
      'Amalapuram',
      'Firozpur Cantt.',
      'Vikarabad',
      'Thiruvalla',
      'Sherkot',
      'Palghar',
      'Shegaon',
      'Jangaon',
      'Bheemunipatnam',
      'Panna',
      'Thodupuzha',
      'KathUrban Agglomeration',
      'Palitana',
      'Arwal',
      'Venkatagiri',
      'Kalpi',
      'Rajgarh (Churu)',
      'Sattenapalle',
      'Arsikere',
      'Ozar',
      'Thirumangalam',
      'Petlad',
      'Nasirabad',
      'Phaltan',
      'Rampurhat',
      'Nanjangud',
      'Forbesganj',
      'Tundla',
      'BhabUrban Agglomeration',
      'Sagara',
      'Pithapuram',
      'Sira',
      'Bhadrachalam',
      'Charkhi Dadri',
      'Chatra',
      'Palasa Kasibugga',
      'Nohar',
      'Yevla',
      'Sirhind Fatehgarh Sahib',
      'Bhainsa',
      'Parvathipuram',
      'Shahade',
      'Chalakudy',
      'Narkatiaganj',
      'Kapadvanj',
      'Macherla',
      'Raghogarh-Vijaypur',
      'Rupnagar',
      'Naugachhia',
      'Sendhwa',
      'Byasanagar',
      'Sandila',
      'Gooty',
      'Salur',
      'Nanpara',
      'Sardhana',
      'Vita',
      'Gumia',
      'Puttur',
      'Jalandhar Cantt.',
      'Nehtaur',
      'Changanassery',
      'Mandapeta',
      'Dumka',
      'Seohara',
      'Umarkhed',
      'Madhupur',
      'Vikramasingapuram',
      'Punalur',
      'Kendrapara',
      'Sihor',
      'Nellikuppam',
      'Samana',
      'Warora',
      'Nilambur',
      'Rasipuram',
      'Ramnagar',
      'Jammalamadugu',
      'Nawanshahr',
      'Thoubal',
      'Athni',
      'Cherthala',
      'Sidhi',
      'Farooqnagar',
      'Peddapuram',
      'Chirkunda',
      'Pachora',
      'Madhepura',
      'Pithoragarh',
      'Tumsar',
      'Phalodi',
      'Tiruttani',
      'Rampura Phul',
      'Perinthalmanna',
      'Padrauna',
      'Pipariya',
      'Dalli-Rajhara',
      'Punganur',
      'Mattannur',
      'Mathura',
      'Thakurdwara',
      'Nandivaram-Guduvancheri',
      'Mulbagal',
      'Manjlegaon',
      'Wankaner',
      'Sillod',
      'Nidadavole',
      'Surapura',
      'Rajagangapur',
      'Sheikhpura',
      'Parlakhemundi',
      'Kalimpong',
      'Siruguppa',
      'Arvi',
      'Limbdi',
      'Barpeta',
      'Manglaur',
      'Repalle',
      'Mudhol',
      'Shujalpur',
      'Mandvi',
      'Thangadh',
      'Sironj',
      'Nandura',
      'Shoranur',
      'Nathdwara',
      'Periyakulam',
      'Sultanganj',
      'Medak',
      'Narayanpet',
      'Raxaul Bazar',
      'Rajauri',
      'Pernampattu',
      'Nainital',
      'Ramachandrapuram',
      'Vaijapur',
      'Nangal',
      'Sidlaghatta',
      'Punch',
      'Pandhurna',
      'Wadgaon Road',
      'Talcher',
      'Varkala',
      'Pilani',
      'Nowgong',
      'Naila Janjgir',
      'Mapusa',
      'Vellakoil',
      'Merta City',
      'Sivaganga',
      'Mandideep',
      'Sailu',
      'Vyara',
      'Kovvur',
      'Vadalur',
      'Nawabganj',
      'Padra',
      'Sainthia',
      'Siana',
      'Shahpur',
      'Sojat',
      'Noorpur',
      'Paravoor',
      'Murtijapur',
      'Ramnagar',
      'Sundargarh',
      'Taki',
      'Saundatti-Yellamma',
      'Pathanamthitta',
      'Wadi',
      'Rameshwaram',
      'Tasgaon',
      'Sikandra Rao',
      'Sihora',
      'Tiruvethipuram',
      'Tiruvuru',
      'Mehkar',
      'Peringathur',
      'Perambalur',
      'Manvi',
      'Zunheboto',
      'Mahnar Bazar',
      'Attingal',
      'Shahbad',
      'Puranpur',
      'Nelamangala',
      'Nakodar',
      'Lunawada',
      'Murshidabad',
      'Mahe',
      'Lanka',
      'Rudauli',
      'Tuensang',
      'Lakshmeshwar',
      'Zira',
      'Yawal',
      'Thana Bhawan',
      'Ramdurg',
      'Pulgaon',
      'Sadasivpet',
      'Nargund',
      'Neem-Ka-Thana',
      'Memari',
      'Nilanga',
      'Naharlagun',
      'Pakaur',
      'Wai',
      'Tarikere',
      'Malavalli',
      'Raisen',
      'Lahar',
      'Uravakonda',
      'Savanur',
      'Sirohi',
      'Udhampur',
      'Umarga',
      'Pratapgarh',
      'Lingsugur',
      'Usilampatti',
      'Palia Kalan',
      'Wokha',
      'Rajpipla',
      'Vijayapura',
      'Rawatbhata',
      'Sangaria',
      'Paithan',
      'Rahuri',
      'Patti',
      'Zaidpur',
      'Lalsot',
      'Maihar',
      'Vedaranyam',
      'Nawapur',
      'Solan',
      'Vapi',
      'Sanawad',
      'Warisaliganj',
      'Revelganj',
      'Sabalgarh',
      'Tuljapur',
      'Simdega',
      'Musabani',
      'Kodungallur',
      'Phulabani',
      'Umreth',
      'Narsipatnam',
      'Nautanwa',
      'Rajgir',
      'Yellandu',
      'Sathyamangalam',
      'Pilibanga',
      'Morshi',
      'Pehowa',
      'Sonepur',
      'Pappinisseri',
      'Zamania',
      'Mihijam',
      'Purna',
      'Puliyankudi',
      'Shikarpur, Bulandshahr',
      'Umaria',
      'Porsa',
      'Naugawan Sadat',
      'Fatehpur Sikri',
      'Manuguru',
      'Udaipur',
      'Pipar City',
      'Pattamundai',
      'Nanjikottai',
      'Taranagar',
      'Yerraguntla',
      'Satana',
      'Sherghati',
      'Sankeshwara',
      'Madikeri',
      'Thuraiyur',
      'Sanand',
      'Rajula',
      'Kyathampalle',
      'Shahabad, Rampur',
      'Tilda Newra',
      'Narsinghgarh',
      'Chittur-Thathamangalam',
      'Malaj Khand',
      'Sarangpur',
      'Robertsganj',
      'Sirkali',
      'Radhanpur',
      'Tiruchendur',
      'Utraula',
      'Patratu',
      'Vijainagar, Ajmer',
      'Periyasemur',
      'Pathri',
      'Sadabad',
      'Talikota',
      'Sinnar',
      'Mungeli',
      'Sedam',
      'Shikaripur',
      'Sumerpur',
      'Sattur',
      'Sugauli',
      'Lumding',
      'Vandavasi',
      'Titlagarh',
      'Uchgaon',
      'Mokokchung',
      'Paschim Punropara',
      'Sagwara',
      'Ramganj Mandi',
      'Tarakeswar',
      'Mahalingapura',
      'Dharmanagar',
      'Mahemdabad',
      'Manendragarh',
      'Uran',
      'Tharamangalam',
      'Tirukkoyilur',
      'Pen',
      'Makhdumpur',
      'Maner',
      'Oddanchatram',
      'Palladam',
      'Mundi',
      'Nabarangapur',
      'Mudalagi',
      'Samalkha',
      'Nepanagar',
      'Karjat',
      'Ranavav',
      'Pedana',
      'Pinjore',
      'Lakheri',
      'Pasan',
      'Puttur',
      'Vadakkuvalliyur',
      'Tirukalukundram',
      'Mahidpur',
      'Mussoorie',
      'Muvattupuzha',
      'Rasra',
      'Udaipurwati',
      'Manwath',
      'Adoor',
      'Uthamapalayam',
      'Partur',
      'Nahan',
      'Ladwa',
      'Mankachar',
      'Nongstoin',
      'Losal',
      'Sri Madhopur',
      'Ramngarh',
      'Mavelikkara',
      'Rawatsar',
      'Rajakhera',
      'Lar',
      'Lal Gopalganj Nindaura',
      'Muddebihal',
      'Sirsaganj',
      'Shahpura',
      'Surandai',
      'Sangole',
      'Pavagada',
      'Tharad',
      'Mansa',
      'Umbergaon',
      'Mavoor',
      'Nalbari',
      'Talaja',
      'Malur',
      'Mangrulpir',
      'Soro',
      'Shahpura',
      'Vadnagar',
      'Raisinghnagar',
      'Sindhagi',
      'Sanduru',
      'Sohna',
      'Manavadar',
      'Pihani',
      'Safidon',
      'Risod',
      'Rosera',
      'Sankari',
      'Malpura',
      'Sonamukhi',
      'Shamsabad, Agra',
      'Nokha',
      'PandUrban Agglomeration',
      'Mainaguri',
      'Afzalpur',
      'Shirur',
      'Salaya',
      'Shenkottai',
      'Pratapgarh',
      'Vadipatti',
      'Nagarkurnool',
      'Savner',
      'Sasvad',
      'Rudrapur',
      'Soron',
      'Sholingur',
      'Pandharkaoda',
      'Perumbavoor',
      'Maddur',
      'Nadbai',
      'Talode',
      'Shrigonda',
      'Madhugiri',
      'Tekkalakote',
      'Seoni-Malwa',
      'Shirdi',
      'SUrban Agglomerationr',
      'Terdal',
      'Raver',
      'Tirupathur',
      'Taraori',
      'Mukhed',
      'Manachanallur',
      'Rehli',
      'Sanchore',
      'Rajura',
      'Piro',
      'Mudabidri',
      'Vadgaon Kasba',
      'Nagar',
      'Vijapur',
      'Viswanatham',
      'Polur',
      'Panagudi',
      'Manawar',
      'Tehri',
      'Samdhan',
      'Pardi',
      'Rahatgarh',
      'Panagar',
      'Uthiramerur',
      'Tirora',
      'Rangia',
      'Sahjanwa',
      'Wara Seoni',
      'Magadi',
      'Rajgarh (Alwar)',
      'Rafiganj',
      'Tarana',
      'Rampur Maniharan',
      'Sheoganj',
      'Raikot',
      'Pauri',
      'Sumerpur',
      'Navalgund',
      'Shahganj',
      'Marhaura',
      'Tulsipur',
      'Sadri',
      'Thiruthuraipoondi',
      'Shiggaon',
      'Pallapatti',
      'Mahendragarh',
      'Sausar',
      'Ponneri',
      'Mahad',
      'Lohardaga',
      'Tirwaganj',
      'Margherita',
      'Sundarnagar',
      'Rajgarh',
      'Mangaldoi',
      'Renigunta',
      'Longowal',
      'Ratia',
      'Lalgudi',
      'Shrirangapattana',
      'Niwari',
      'Natham',
      'Unnamalaikadai',
      'PurqUrban Agglomerationzi',
      'Shamsabad, Farrukhabad',
      'Mirganj',
      'Todaraisingh',
      'Warhapur',
      'Rajam',
      'Urmar Tanda',
      'Lonar',
      'Powayan',
      'P.N.Patti',
      'Palampur',
      'Srisailam Project (Right Flank Colony) Township',
      'Sindagi',
      'Sandi',
      'Vaikom',
      'Malda',
      'Tharangambadi',
      'Sakaleshapura',
      'Lalganj',
      'Malkangiri',
      'Rapar',
      'Mauganj',
      'Todabhim',
      'Srinivaspur',
      'Murliganj',
      'Reengus',
      'Sawantwadi',
      'Tittakudi',
      'Lilong',
      'Rajaldesar',
      'Pathardi',
      'Achhnera',
      'Pacode',
      'Naraura',
      'Nakur',
      'Palai',
      'Morinda, India',
      'Manasa',
      'Nainpur',
      'Sahaspur',
      'Pauni',
      'Prithvipur',
      'Ramtek',
      'Silapathar',
      'Songadh',
      'Safipur',
      'Sohagpur',
      'Mul',
      'Sadulshahar',
      'Phillaur',
      'Sambhar',
      'Prantij',
      'Nagla',
      'Pattran',
      'Mount Abu',
      'Reoti',
      'Tenu dam-cum-Kathhara',
      'Panchla',
      'Sitarganj',
      'Pasighat',
      'Motipur',
      'O Valley',
      'Raghunathpur',
      'Suriyampalayam',
      'Qadian',
      'Rairangpur',
      'Silvassa',
      'Nowrozabad (Khodargama)',
      'Mangrol',
      'Soyagaon',
      'Sujanpur',
      'Manihari',
      'Sikanderpur',
      'Mangalvedhe',
      'Phulera',
      'Ron',
      'Sholavandan',
      'Saidpur',
      'Shamgarh',
      'Thammampatti',
      'Maharajpur',
      'Multai',
      'Mukerian',
      'Sirsi',
      'Purwa',
      'Sheohar',
      'Namagiripettai',
      'Parasi',
      'Lathi',
      'Lalganj',
      'Narkhed',
      'Mathabhanga',
      'Shendurjana',
      'Peravurani',
      'Mariani',
      'Phulpur',
      'Rania',
      'Pali',
      'Pachore',
      'Parangipettai',
      'Pudupattinam',
      'Panniyannur',
      'Maharajganj',
      'Rau',
      'Monoharpur',
      'Mandawa',
      'Marigaon',
      'Pallikonda',
      'Pindwara',
      'Shishgarh',
      'Patur',
      'Mayang Imphal',
      'Mhowgaon',
      'Guruvayoor',
      'Mhaswad',
      'Sahawar',
      'Sivagiri',
      'Mundargi',
      'Punjaipugalur',
      'Kailasahar',
      'Samthar',
      'Sakti',
      'Sadalagi',
      'Silao',
      'Mandalgarh',
      'Loha',
      'Pukhrayan',
      'Padmanabhapuram',
      'Belonia',
      'Saiha',
      'Srirampore',
      'Talwara',
      'Puthuppally',
      'Khowai',
      'Vijaypur',
      'Takhatgarh',
      'Thirupuvanam',
      'Adra',
      'Piriyapatna',
      'Obra',
      'Adalaj',
      'Nandgaon',
      'Barh',
      'Chhapra',
      'Panamattom',
      'Niwai',
      'Bageshwar',
      'Tarbha',
      'Adyar',
      'Narsinghgarh',
      'Warud',
      'Asarganj',
      'Sarsod',
    ]
    this.temp.city='All';
    this.price.city='All';
    this.cityCtrl.setValue('All');
  }

  filterCities() {
    this.filteredOptions = this.cityCtrl.valueChanges
    .pipe(
      startWith(''),
      map(val => this.filter(val))
    );
  }

  filterCustomer(val:string){
    return this.customers.filter(option=>
      option.name.toLowerCase().includes(val.toLowerCase()))
  }

  filterVehicleGroup(val:string){
    return this.vehicleGroup.filter(option=>
      option.name.toLowerCase().includes(val.toLowerCase())
      );
  }

  filterDutyType(val:string){
    return this.dutyTypes.filter(option=>
      option.name.toLowerCase().includes(val.toLowerCase()))
  }

  filter(val: string): string[] {
    return this.city.filter(option =>
      option.toLowerCase().startsWith(val.toLowerCase()));
  }
  
  change(temp:any,i:any)
  {
    console.log(temp.id)
    this.price.ownerId=this.user.ownerId;
    this.price.baseRate=temp.baseRate;
    this.price.extraHrs=temp.extraHrs;
    this.price.extraKm=temp.extraKm;
    this.price.dutyTYpeId=temp.dutyTypeId;
    this.price.id=temp.id
    this.priceService.updatePrice(this.price).subscribe(res=>{
      
      if(res.insertId)
        this.priceArray[i].id=res.insertId

      this.snackBar.open("Updated","X",{duration:2000})
    })
  }

  selectedCustomer:Customer={}

  copyFrom()
  {
    this.dialog.open(CustomerselectionComponent,{autoFocus:false}).afterClosed().subscribe(data=>{
      this.selectedCustomer=data;
      
      this.priceService.copyPricing({customerId:this.price.customerId,fromCustomerId:this.selectedCustomer.id}).subscribe(data=>{
        if(data)
        this.snackBar.open("Prices copied from "+this.selectedCustomer.name+" to "+this.customerCopyName,"X",{duration:2000})
      })
      
    })
  }

  dutyTypes:any;
  vehicleGroup:VehicleGroup[];
  vehicleGroup0:any;
  vehicleGroupCtrl: FormControl = new FormControl();
  dutyTypeCtrl: FormControl = new FormControl();

  price:Price={
    dutyTYpeId:'',
    vehicleGroupId:'',
    customerId:'',
    city:'',
    baseRate:null,
    extraKm:null,
    extraHrs:null,
    id:null,
    ownerId:'',
  }
  temp:any={
    city:'',
    vehicleGroupId:'',
    customerId:'',
    ownerId:''
  }
  
  

}