import { Component, OnInit, Inject, HostListener } from '@angular/core';
import { FormGroup, FormBuilder, FormControl } from '@angular/forms';
import { AuthService } from '../../../core/auth.service';
import { AirlineService } from '../airlinedisp/airline.service';
import * as moment from 'moment';
import { CustomerService } from '../../masters/customer/customer.service';
import { Customer } from '../../masters/customer';
import { startWith } from 'rxjs/operators/startWith';
import { map } from 'rxjs/operators/map';
import { Observable } from 'rxjs/Observable';
import { BookingsService } from '../../operations/bookings.service';
import { MatDialogRef, MAT_DIALOG_DATA, MatDialog, MatSnackBar } from '@angular/material';
import { User } from '../../../core/user';
import { EmployeeService } from '../../masters/new-employees/employee.service';
import { ActivitylogService } from '../../../activitylog.service';

@Component({
  selector: 'bookairline',
  templateUrl: './bookairline.component.html',
  styleUrls: ['./bookairline.component.scss']
})
export class BookairlineComponent implements OnInit {

  @HostListener("window:beforeunload", ["$event"]) unloadHandler(event: Event) {
    console.log("Processing beforeunload...");
    event.returnValue = false;
  }

  filteredOptions: any;
  roundTrip: any;
  internationalFlight: boolean;
  connectingFlight: boolean;
  connectingReturnFlight: boolean;
  bookFlight: FormGroup;
  editState: boolean;

  domesticFromCtrl: FormControl = new FormControl();
  domesticToCtrl: FormControl = new FormControl();
  internationalFromCtrl: FormControl = new FormControl();
  internationalToCtrl: FormControl = new FormControl();
  domesticConnectingFromCtrl: FormControl = new FormControl();
  domesticConnectingToCtrl: FormControl = new FormControl();
  internationalConnectingFromCtrl: FormControl = new FormControl();
  internationalConnectingToCtrl: FormControl = new FormControl();
  domesticConnectingReturnFromCtrl: FormControl = new FormControl();
  domesticConnectingReturnToCtrl: FormControl = new FormControl();
  internationalConnectingReturnFromCtrl: FormControl = new FormControl();
  internationalConnectingReturnToCtrl: FormControl = new FormControl();
  domesticAirportsFrom: any;    
  domesticAirportsTo: any;    
  internationalAirportFrom: any;
  internationalAirportTo: any;
  domesticConnectingAirportFrom: any;
  domesticConnectingAirportTo: any;
  internationalConnectingAirportFrom: any;
  internationalConnectingAirportTo: any;
  domesticConnectingReturnAirportFrom: any;
  domesticConnectingReturnAirportTo: any;
  internationalConnectingReturnAirportFrom: any;
  internationalConnectingReturnAirportTo: any;

  customerCtrl: FormControl = new FormControl();
  customers: any[];
  customer: any;

  bookByCtrl: FormControl = new FormControl();
  bookBy: Observable<string[]>;
  bookByArr: any[];

  from = new FormControl();
  user: User={};
  ws:WebSocket;

  airports: string[] = [
  'Agartala, IXA',
  'Agatti Island, AGX',
  'Agra, AGR',    
  'Ahmedabad, AMD',    
  'Aizawl, AJL',    
  'Akola, AKD',    
  'Allahabad, IXD',
  'Along, IXV',    
  'Amritsar, ATQ',    
  'Aurangabad, IXU',    
  'Bangalore, BLR',    
  'Bareilly, BEK',    
  'Bathinda, BUP',    
  'Belgaum, IXG',    
  'Bellary, BEP',    
  'Bellary, VDY',    
  'Bhavnagar, BHU',    
  'Bhopal, BHO',    
  'Bhubaneswar, BBI',
  'Bhuj, BHJ',    
  'Bikaner, BKB',
  'Bilaspur, PAB',
  'Car Nicobar, CBD',
  'Chandigarh, IXC',
  'Chennai, MAA',
  'Coimbatore, CJB',
  'Cooch Behar, COH',
  'Daman, NMB',
  'Dehradun, DED',
  'Delhi, DEL',
  'Dhanbad, DBD',
  'Dharmsala, DHM',
  'Dibrugarh, DIB',
  'Dimapur, DMU',
  'Diu, DIU',
  'Durgapur, RDP',
  'Ernakulam, COK',
  'Gaya, GAY',    
  'Goa, GOI',  
  'Gorakhpur, GOP',    
  'Guwahati, GAU',    
  'Gwalior, GWL',    
  'Hubli, HBX',    
  'Hyderabad, HYD',    
  'Imphal, IMF',    
  'Indore, IDR',    
  'Jabalpur, JLR',    
  'Jagdalpur, JGB',    
  'Jaipur, JAI',    
  'Jaisalmer, JSA',    
  'Jammu, IXJ',    
  'Jamnagar, JGA',    
  'Jamshedpur, IXW',    
  'Jodhpur, JDH',    
  'Jorhat, JRH',    
  'Kadapa, CDP',    
  'Kailasahar, IXH',    
  'Kamalpur, IXQ',    
  'Kandla, IXY',    
  'Kanpur, KNU',    
  'Keshod, IXK',    
  'Khajuraho, HJR',    
  'Kolhapur, KLH',    
  'Kolkata, CCU',    
  'Kota, KTU',    
  'Kozhikode, CCJ',    
  'Kullu, KUU',    
  'Latur, LTU',    
  'Leh, IXL',    
  'Lilabari, IXI',    
  'Lucknow, LKO',    
  'Ludhiana, LUH',    
  'Madurai, IXM',    
  'Maldah, LDA',    
  'Mangalore, IXE',    
  'Mohanbari, MOH',  
  'Mumbai, BOM',    
  'Mysore, MYQ',    
  'Nagpur, NAG',    
  'Nalchik, NAL',    
  'Nanded, NDC',  
  'Nashik, ISK',    
  'Neiveli, NVY',   
  'Pantnagar, PGH',    
  'Pasighat, IXT',  
  'Pathankot, IXP',    
  'Patna, PAT',    
  'Pondicherry, PNY',    
  'Porbandar, PBD',    
  'Port Blair, IXZ',    
  'Pune, PNQ',    
  'Puttaparthi, PUT',    
  'Raipur, RPR',    
  'Rajahmundry, RJA',    
  'Rajkot, RAJ',    
  'Rajouri, RJI',    
  'Ranchi, IXR',    
  'Raurkela, RRK',    
  'Rewa, REW',    
  'Rupshi, RUP',    
  'Salem, SXV',    
  'Satna, TNI',    
  'Shillong, SHL',    
  'Shimla, SLV',    
  'Shirdi, SAG',    
  'Silchar, IXS',    
  'Siliguri, IXB',    
  'Skardu, KDU',    
  'Solapur, SSE',    
  'Srinagar, SXR',    
  'Surat, STV',    
  'Tezpur, TEZ',    
  'Tezu, TEI',    
  'Thiruvananthapuram, TRV',    
  'Thoothukkudi, TCR',    
  'Tiruchirappalli, TRZ',    
  'Tirupati, TIR',    
  'Udaipur, UDR',    
  'Vadodara, BDQ',  
  'Varanasi, VNS',    
  'Vijayawada, VGA',    
  'Visakhapatnam, VTZ',    
  'Warrangal, WGC' 
]

  internationalAirports: string[] = [  
  'Aarhus, Denmark, AAR',
  'Abadan, Iran, ABD',
  'Abeche, Chad, AEH',
  'Aberdeen, United Kingdom, ABZ',
  'Aberdeen (SD), USA, ABR',
  'Abidjan, Cote d\'Ivoire, ABJ',
  'Abilene (TX), USA, ABI',
  'Abu Dhabi, United Arab Emirates, AUH',
  'Abuja, Nigeria, ABV',
  'Abu Rudeis, Egypt, AUE',
  'Abu Simbel, Egypt, ABS',
  'Acapulco, Mexico, ACA',
  'Accra, Ghana, ACC',
  'Adana, Turkey, ADA',
  'Addis Ababa, Ethiopia, ADD',
  'Adelaide, Australia, ADL',
  'Aden, Yemen, ADE',
  'Adiyaman, Turkey, ADF',
  'Adler/Sochi, Russia, AER',
  'Agades, Niger, AJY',
  'Agadir, Morocco, AGA',
  'Agana (Hagåtña), Guam, SUM',
  'Aggeneys, South Africa, AGZ',
  'Aguadilla, Puerto Rico, BQN',
  'Aguascaliente, Mexico, AGU',
  'Ahmedabad, India, AMD',
  'Aiyura, Papua New Guinea, AYU',
  'Ajaccio, France, AJA',
  'Akita, Japan, AXT',
  'Akron (OH), USA, CAK',
  'Akrotiri, Cyprus, AKT',
  'Al Ain, United Arab Emirates, AAN',
  'Al Arish, Egypt, AAC',
  'Albany, Australia, ALH',
  'Albany (GA), USA, ABY',
  'Albany (NY), USA, ALB',
  'Albi, France, LBI',
  'Alborg, Denmark, AAL',
  'Albuquerque (NM), USA, ABQ',
  'Albury, Australia, ABX',
  'Alderney, Channel Islands, ACI',
  'Aleppo, Syria, ALP',
  'Alesund, Norway, AES',
  'Alexander Bay, South Africa, ALJ',
  'Alexandria - Borg el Arab Airport, Egypt, HBH',
  'Alexandria - El Nhouza Airport, Egypt, ALY',
  'Alexandria - Esler Field, USA (LA), ESF',
  'Alfujairah (Fujairah), United Arab Emirates, FJR',
  'Alghero Sassari, Italy, AHO',
  'Algiers, Algeria, ALG',
  'Al Hoceima, Morocco, AHU',
  'Alicante, Spain, ALC',
  'Alice Springs, Australia, ASP',
  'Alldays, South Africa, ADY',
  'Allentown (PA), USA, ABE',
  'Almaty (Alma Ata), Kazakhstan, ALA',
  'Almeria, Spain, LEI',
  'Alta, Norway, ALF',
  'Altay, PR China, AAT',
  'Altenrhein, Switzerland, ACH',
  'Altoona (PA), USA, AOO',
  'Altus, USA, AXS',
  'Amami, Japan, ASJ',
  'Amarillo (TX), USA, AMA',
  'Amazon Bay, Papua New Guinea, AZB',
  'Amman - Queen Alia International Airport, Jordan, AMM',
  'Amman - Amman-Marka International Airport, Jordan, ADJ',
  'Amritsar, India, ATQ',
  'Amsterdam, Netherlands, AMS',
  'Anand, India, QNB',
  'Anchorage (AK), USA, ANC',
  'Ancona - Ancona Falconara Airport, Italy, AOI',
  'Andorra La Vella - Heliport, Andorra, ALV',
  'Anguilla, Anguilla, AXA',
  'Anjouan, Comoros (Comores), AJN',
  'Ankara, Turkey, ANK',
  'Ankara, Turkey, ESB',
  'Annaba, Algeria, AAE',
  'Ann Arbor (MI), USA, ARB',
  'Annecy, France, NCY',
  'Anniston (AL), USA, ANB',
  'Antalya, Turkey, AYT',
  'Antananarivo (Tanannarive), Madagascar, TNR',
  'Antigua, Antigua and Barbuda, ANU',
  'Antwerp, Belgium, ANR',
  'Aomori, Japan, AOJ',
  'Apia, Samoa, APW',
  'Appelton/Neenah/Menasha (WI), USA, ATW',
  'Aqaba, Jordan, AQJ',
  'Aracaju, Brazil, AJU',
  'Arkhangelsk, Russia, ARH',
  'Arusha, Tanzania, ARK',
  'Araxos, Greece, GPA',
  'Arlit, Niger, RLT',
  'Arrecife/Lanzarote, Spain, ACE',
  'Aruba, Oranjestad, Aruba, AUA',
  'Asheville (NC), USA, AVL',
  'Ashgabat, Turkmenistan, ASB',
  'Asmara, Eritrea, ASM',
  'Aspen, USA, ASE',
  'Assiut, Egypt, ATZ',
  'Astana, Kazakhstan, TSE',
  'Asuncion, Paraguay, ASU',
  'Aswan, Egypt, ASW',
  'Athens, Greece, ATH',
  'Athens, Hellinikon Airport, Greece, HEW',
  'Athens (GA), USA, AHN',
  'Athens (OH), USA, ATO',
  'Atlanta (GA), USA, ATL',
  'Atlantic City (NJ), USA, ACY',
  'Attawapiskat, NT, Canada, YAT',
  'Auckland, New Zealand, AKL',
  'Augsburg, Germany, AGB',
  'Augusta (GA), USA, AGS',
  'Augusta (ME), USA, AUG',
  'Aurillac, France, AUR',
  'Austin (TX), USA, AUS',
  'Ayawasi, Indonesia, AYW',
  'Ayers Rock - Connellan, Australia, AYQ',
  'Ayr, Australia, AYR',
  'Badajoz, Spain, BJZ',
  'Bagdad, Iraq, BGW',
  'Bagdogra, India, IXB',
  'Bahamas, The Bahamas, NAS',
  'Bahawalpur, Pakistan, BHV',
  'Bahrain, Bahrain, BAH',
  'Bakersfield (CA), USA, BFL',
  'Baku , Azerbaijan, BAK',
  'Ballina, Australia, BNK',
  'Baltimore (MD), USA, BWI',
  'Bamaga, Australia, ABM',
  'Bamako, Mali, BKO',
  'Bambari, Central African Republic, BBY',
  'Bandar Seri Begawan, Brunei, BWN',
  'Bandung, Indonesia, BDO',
  'Bangalore, India, BLR',
  'Bangassou, Central African Republic, BGU',
  'Bangkok, Don Muang, Thailand, DMK',
  'Bangkok, Thailand, BKK',
  'Bangor (ME), USA, BGR',
  'Bangui, Central African Republic, BGF',
  'Banjul, Gambia, BJL',
  'Bannu, Pakistan, BNP',
  'Barcelona, Spain, BCN',
  'Barcelona, Venezuela, BLA',
  'Bardufoss, Norway, BDU',
  'Bari, Italy, BRI',
  'Barisal, Bangladesh, BZL',
  'Baroda, India, BDQ',
  'Barra, United Kingdom, BRR',
  'Barranquilla, Colombia, BAQ',
  'Basel, Switzerland, BSL',
  'Basel/Mulhouse, Switzerland/France, EAP',
  'Basra, Basrah, Iraq, BSR',
  'Basse-Terre, Guadeloupe, PTP',
  'Basseterre, Saint Kitts and Nevis, SKB',
  'Bastia, France, BIA',
  'Baton Rouge (LA), USA, BTR',
  'Bayreuth, Germany, BYU',
  'Beaumont/Pt. Arthur (TX), USA, BPT',
  'Beckley (WV), USA, BKW',
  'Beef Island, Virgin Islands (British), EIS',
  'Beijing, China, PEK',
  'Beijing - Nanyuan Airport, China, NAY',
  'Beira, Mozambique, BEW',
  'Beirut, Lebanon, BEY',
  'Belem, Brazil, BEL',
  'Belfast - George Best Belfast City Airport, United Kingdom, BHD',
  'Belfast - Belfast International Airport, United Kingdom, BFS',
  'Belgaum, India, IXG',
  'Belgrad (Beograd), Serbia, BEG',
  'Belize City , Belize, BZE',
  'Bellingham (WA), USA, BLI',
  'Belo Horizonte, Brazil, CNF',
  'Bemidji (MN), USA, BJI',
  'Benbecula, United Kingdom, BEB',
  'Benghazi (Bengasi), Libya, BEN',
  'Benguela, Angola, BUG',
  'Benton Harbour (MI), USA, BEH',
  'Berberati, Central African Republic, BBT',
  'Bergamo/Milan , Italy, BGY',
  'Bergen, Norway, BGO',
  'Bergerac - Roumanieres, France, EGC',
  'Berlin, Germany, BER',
  'Berlin, Schoenefeld, Germany, SXF',
  'Berlin, Tegel, Germany, TXL',
  'Berlin, Tempelhof, Germany, THF',
  'Bermuda -, Bermuda, BDA',
  'Berne, Bern-Belp, Switzerland, BRN',
  'Berne, Railway Service, Switzerland, ZDJ',
  'Bethel (AK), USA, BET',
  'Bhopal, India, BHO',
  'Bhubaneswar, India, BBI',
  'Biarritz, France, BIQ',
  'Bilbao, Spain, BIO',
  'Billings (MT), USA, BIL',
  'Billund, Denmark, BLL',
  'Bintulu, Malaysia, BTU',
  'Biraro, Central African Republic, IRO',
  'Birmingham, United Kingdom, BHX',
  'Birmingham (AL), USA, BHM',
  'Bishkek, Kyrgyzstan, FRU',
  'Bismarck (ND), USA, BIS',
  'Bissau, Guinea-Bissau, BXO',
  'Blackpool, United Kingdom, BLK',
  'Blackwater, Australia, BLT',
  'Blantyre (Mandala), Malawi, BLZ',
  'Blenheim, New Zealand, BHE',
  'Bloemfontein, South Africa, BFN',
  'Bloomington (IL), USA, BMI',
  'Bloomington (IN), USA, BMG',
  'Bluefield (WV), USA, BLF',
  'Boa Vista, Brazil, BVB',
  'Bobo/Dioulasso, Burkina Faso, BOY',
  'Bodo, Norway, BOO',
  'Bodrum, Turkey, BJV',
  'Bogota, Colombia, BOG',
  'Boise (ID), USA, BOI',
  'Bologna, Italy, BLQ',
  'Bombay (Mumbai), India, BOM',
  'Bonaire, Netherlands Antilles, BON',
  'Bonaventure, PQ, Canada, YVB',
  'Bora Bora, French Polynesia, BOB',
  'Bordeaux - Bordeaux Airport, France, BOD',
  'Borrego Springs (CA), USA, BXS',
  'Boston (MA), USA, BOS',
  'Bouake, Cote d\'Ivoire, BYK',
  'Bourgas/Burgas, Bulgaria, BOJ',
  'Bournemouth, United Kingdom, BOH',
  'Bowen, Australia, ZBO',
  'Bozeman (MT), USA, BZN',
  'Bradford/Warren (PA) /Olean (NY), USA, BFD',
  'Brainerd (MN), USA, BRD',
  'Brampton Island, Australia, BMP',
  'Brasilia, Brazil, BSB',
  'Bratislava, Slovakia, BTS',
  'Brazzaville, Congo (ROC), BZV',
  'Bremen, Germany, BRE',
  'Brescia, Montichiari, Italy, VBS',
  'Brest, France, BES',
  'Bria, Central African Republic, BIV',
  'Bridgeport (CT), USA, BDR',
  'Bridgetown, Barbados, BGI',
  'Brindisi, Italy, BDS',
  'Brisbane, Australia, BNE',
  'Bristol, United Kingdom, BRS',
  'Broennoeysund, Norway, BNN',
  'Broken Hill, Australia, BHQ',
  'Brookings (SD), USA, BKX',
  'Broome, Australia, BME',
  'Brunswick (GA), USA, BQK',
  'Brussels, Belgium, BRU',
  'Bucaramanga, Colombia, BGA',
  'Bucharest, Romania, BUH',
  'Bucharest - Henri Coandă International Airport, Romania, OTP',
  'Budapest, Hungary, BUD',
  'Buenos Aires, Argentina, BUE',
  'Buenos Aires, Ezeiza International Airport, Argentina, EZE',
  'Buenos Aires, Jorge Newbery, Argentina, AEP',
  'Buffalo Range, Zimbabwe, BFO',
  'Buffalo/Niagara Falls (NY), USA, BUF',
  'Bujumbura, Burundi, BJM',
  'Bulawayo, Zimbabwe, BUQ',
  'Bullhead City (NV), USA, BHC',
  'Bundaberg, Australia, BDB',
  'Burbank (CA), USA, BUR',
  'Burlington IA, USA, BRL',
  'Burlington (VT), USA, BTV',
  'Burnie (Wynyard), Australia, BWT',
  'Butte (MT), USA, BTM',
  'Cabinda, Angola, CAB',
  'Cagliari, Italy, CAG',
  'Cairns, Australia, CNS',
  'Cairo, Egypt, CAI',
  'Calama - El Loa, Chile, CJC',
  'Calcutta (Kolkata), India, CCU',
  'Calgary, Canada, YYC',
  'Cali, Colombia, CLO',
  'Calicut, India, CCJ',
  'Calvi, France, CLY',
  'Cambridge Bay, Canada, YCB',
  'Cambrigde, United Kingdom, CBG',
  'Campbeltown, United Kingdom, CAL',
  'Campo Grande, Brazil, CGR',
  'Canberra, Australia, CBR',
  'Cancun, Mexico, CUN',
  'Cannes, France, CEQ',
  'Canouan (island), Saint Vincent & the Grenadines, CIW',
  'Cape Town, South Africa, CPT',
  'Caracas, Venezuela, CCS',
  'Cardiff, United Kingdom, CWL',
  'Carlsbad (CA), USA, CLD',
  'Carnarvon, Australia, CVQ',
  'Carnot, Central African Republic, CRF',
  'Carson City (NV), USA, CSN',
  'Casablanca, Morocco, CAS',
  'Casablanca, Mohamed V, Morocco, CMN',
  'Casa de Campo, Dominican Republic, LRM',
  'Casino, Australia, CSI',
  'Casper (WY), USA, CPR',
  'Castaway, Fiji, CST',
  'Cartagena, Colombia, CTG',
  'Castries, Saint Lucia, SLU',
  'Catania, Italy, CTA',
  'Cayenne, French Guiana, CAY',
  'Cottbus, Germany, CBU',
  'Cebu City, Philippines, CEB',
  'Cedar City (UT), USA, CDC',
  'Cedar Rapids IA, USA, CID',
  'Ceduna, Australia, CED',
  'Cessnock, Australia, CES',
  'Chabarovsk (Khabarovsk), Russia, KHV',
  'Chambery, France, CMF',
  'Champaign (IL), USA, CMI',
  'Chandigarh, India, IXC',
  'Changchun, Jilin, PR China, CGQ',
  'Chania, Greece, CHQ',
  'Chaoyang, Beijing, PR China, CHG',
  'Charleston (SC), USA, CHS',
  'Charleston (WV), USA, CRW',
  'Charlotte (NC), USA, CLT',
  'Charlottesville (VA), USA, CHO',
  'Charters Towers, Australia, CXT',
  'Chattanooga (TN), USA, CHA',
  'Chengdu - Shuangliu, Sichuan, PR China, CTU',
  'Chennai (Madras), India, MAA',
  'Cheyenne (WY), USA, CYS',
  'Chiang Mai, Thailand, CNX',
  'Chiba City, Japan, QCB',
  'Chicago (IL), Midway, USA, MDW',
  'Chicago (IL), O\'Hare International Airport, USA, ORD',
  'Chicago (IL), USA, CHI',
  'Chichen Itza, Mexico, CZA',
  'Chico (CA), USA, CIC',
  'Chihuahua, Mexico, CUU',
  'Chios, Greece, JKH',
  'Chipata, Zambia, CIP',
  'Chisinau, Moldova, KIV',
  'Chita (Tschita), Russia, HTA',
  'Sapporo, Japan, CTS',
  'Chitral, Pakistan, CJL',
  'Chittagong, Bangladesh, CGP',
  'Chongqing, Sichuan, PR China, CKG',
  'Christchurch, New Zealand, CHC',
  'Chub Cay, Bahamas, CCZ',
  'Churchill, Canada, YYQ',
  'Cienfuegos, Cuba, CFG',
  'Cincinnati (OH), USA, CVG',
  'Ciudad Del Carmen, Mexico, CME',
  'Ciudad Guayana, Venezuela, CGU',
  'Ciudad Juarez, Mexico, CJS',
  'Ciudad Obregon, Mexico, CEN',
  'Ciudad Victoria, Mexico, CVM',
  'Clarksburg (WV), USA, CKB',
  'Clermont, Australia, CMQ',
  'Clermont Ferrand, France, CFE',
  'Cleveland (OH) , Burke Lakefront, USA, BKL',
  'Cleveland (OH) - Cleveland Hopkins International, USA, CLE',
  'Cochabamba, Bolivia, CBB',
  'Cochin, India, COK',
  'Cody/Powell/Yellowstone (WY), USA, COD',
  'Coffmann Cove (AK), USA, KCC',
  'Coffs Harbour, Australia, CFS',
  'Coimbatore, India, CJB',
  'Colima, Mexico, CLQ',
  'College Station/Bryan (TX), USA, CLL',
  'Collinsville, Australia, KCE',
  'Cologne, Germany, CGN',
  'Colombo, Sri Lanka, CMB',
  'Colorado Springs (CO), USA, COS',
  'Columbia (SC), USA, CAE',
  'Columbus (GA), USA, CSG',
  'Columbus (OH), USA, CMH',
  'Conakry, Guinea, CKY',
  'Concord (CA) - Buchanan Field, USA, CCR',
  'Concord (NH) - Concord Municipal Airport, USA, CON',
  'Constantine, Algeria, CZL',
  'Constanta (Constanța), Romania, CND',
  'Coober Pedy, Australia, CPD',
  'Cooktown, Australia, CTN',
  'Cooma, Australia, OOM',
  'Copenhagen, Denmark, CPH',
  'Cordoba, Argentina, COR',
  'Cordoba, Spain, ODB',
  'Cordova (AK), USA, CDV',
  'Corfu, Greece, CFU',
  'Cork, Ireland, ORK',
  'Corpus Christi (TX), USA, CRP',
  'Cotonou, Benin, COO',
  'Coventry, United Kingdom, CVT',
  'Cozmel, Mexico, CZM',
  'Craig (AK), USA, CGA',
  'Crescent City (CA), USA, CEC',
  'Cuiaba, Brazil, CGB',
  'Culiacan, Mexico, CUL',
  'Curacao, Netherlands Antilles, CUR',
  'Curitiba, Brazil, CWB',
  'Cuyo, Philippines, CYU',
  'Dakar, Senegal, DKR',
  'Dalaman, Turkey, DLM',
  'Dalby, Australia, DBY',
  'Dalian, Liaoning, PR China, DLC',
  'Dallas (TX) , Love Field, USA, DAL',
  'Dallas/Ft. Worth (TX), USA, DFW',
  'Daloa, Cote d\'Ivoire, DJO',
  'Damascus, Syria, DAM',
  'Dammam, Saudi Arabien, DMM',
  'Danville (VA), USA, DAN',
  'Dar es Salam (Daressalam), Tanzania, DAR',
  'Darwin, Australia, DRW',
  'Daydream Island, Australia, DDI',
  'Dayton (OH), USA, DAY',
  'Daytona Beach (FL), USA, DAB',
  'Decatur (IL), USA, DEC',
  'Deer Lake/Corner Brook, Canada, YDF',
  'Delhi, India, DEL',
  'Den Haag (The Hague), Netherlands, HAG',
  'Denizli, Turkey, DNZ',
  'Denpasar/Bali, Indonesia, DPS',
  'Denver (CO), USA, DEN',
  'Dera Ismail Khan, Pakistan, DSK',
  'Derby, Australia, DRB',
  'Derry (Londonderry), United Kingdom, LDY',
  'Des Moines (IA), USA, DSM',
  'Detroit (MI) , Coleman A. Young Municipal, USA, DET',
  'Detroit (MI) , Wayne County Airport, USA, DTW',
  'Detroit (MI) , Metropolitan Area, USA, DTT',
  'Devils Lake (ND), USA, DVL',
  'Devonport, Australia, DPO',
  'Dhahran, Saudi Arabia, DHA',
  'Dhaka, Bangladesh, DAC',
  'Dili, Timor Leste (East Timor), DIL',
  'Dillingham (AK), USA, DLG',
  'Dinard, France, DNR',
  'Disneyland Paris, France, DLP',
  'Djerba, Tunisia, DJE',
  'Djibouti (city), Djibouti, JIB',
  'Dodoma, Tanzania, DOD',
  'Doha, Qatar, DOH',
  'Doncaster/Sheffield, United Kingdom, DSA',
  'Donegal (Carrickfin), Ireland, CFN',
  'Dortmund, Germany, DTM',
  'Dothan (AL), USA, DHN',
  'Douala, Cameroon, DLA',
  'Dresden, DRS',
  'Dubai, United Arab Emirates, DXB',
  'Dubbo, Australia, DBO',
  'Dublin, Ireland, DUB',
  'Dubois (PA), USA, DUJ',
  'Dubrovnik, Croatia (Hrvatska), DBV',
  'Dubuque IA, USA, DBQ',
  'Duesseldorf, Germany, DUS',
  'Duluth (MN) /Superior (WI), USA, DLH',
  'Dundee, United Kingdom, DND',
  'Dunedin, New Zealand, DUD',
  'Dunk Island, Australia, DKI',
  'Durango (CO), USA, DRO',
  'Durban, South Africa, DUR',
  'Dushanbe (Duschanbe), Tajikistan, DYU',
  'Dutch Harbor (AK), USA, DUT',
  'Dysart, Australia, DYA',
  'Dzaoudzi, Mayotte, DZA',
  'East London, South Africa, ELS',
  'Easter Island, Chile, IPC',
  'Eau Clarie (WI), USA, EAU',
  'Edinburgh, Scotland, UK, EDI',
  'Edmonton, Canada, YEA',
  'Edmonton, International, Canada, YEG',
  'Edmonton, Municipal, Canada, YXD',
  'Egilsstadir, Iceland, EGS',
  'Eindhoven, Netherlands, EIN',
  'Samana, Dominican Republic, AZS',
  'Elba Island, Marina Di Campo, Italy, EBA',
  'Elat, Israel, ETH',
  'Elat, Ovula, Israel, VDA',
  'Elkhart (IN), USA, EKI',
  'Elko (NV), USA, EKO',
  'Ellisras, South Africa, ELL',
  'El Minya, Egypt, EMY',
  'Elmira (NY), USA, ELM',
  'El Paso (TX), USA, ELP',
  'Ely (NV), USA, ELY',
  'Emerald, Australia, EDR',
  'Emerald, Australia, EMD',
  'Enontekioe, Finland, ENF',
  'Entebbe, Uganda, EBB',
  'Erfurt, Germany, ERF',
  'Erie (PA), USA, ERI',
  'Eriwan (Yerevan, Jerevan), Armenia, EVN',
  'Erzincan, Turkey, ERC',
  'Erzurum, Turkey, ERZ',
  'Esbjerg, Denmark, EBJ',
  'Escanaba (MI), USA, ESC',
  'Esperance, Australia, EPR',
  'Eugene (OR), USA, EUG',
  'Eureka (CA), USA, ACV',
  'Evansville (IN), USA, EVV',
  'Evenes, Norway, EVE',
  'Exeter, United Kingdom, EXT',
  'Fairbanks (AK), USA, FAI',
  'Fair Isle (Shetland), United Kingdom, FIE',
  'Faisalabad, Pakistan, LYP',
  'Fargo (ND) (MN), USA, FAR',
  'Farmington (NM), USA, FMN',
  'Faro, Portugal, FAO',
  'Faroer, Denmark, FAE',
  'Fayetteville (AR), USA, FYV',
  'Fayetteville/Ft. Bragg (NC), USA, FAY',
  'Fes, Morocco, FEZ',
  'Figari, France, FSC',
  'Flagstaff (AZ), USA, FLG',
  'Flin Flon, Canada, YFO',
  'Flint (MI), USA, FNT',
  'Florence (Firenze), Italy, FLR',
  'Florence (SC), USA, FLO',
  'Florianopolis, Brazil, FLN',
  'Floro, Norway, FRO',
  'Fort Albert, Canada, YFA',
  'Fortaleza, Brazil, FOR',
  'Fort de France, Martinique, FDF',
  'Fort Dodge IA, USA, FOD',
  'Fort Huachuca/Sierra Vista (AZ), USA, FHU',
  'Fort Lauderdale/Hollywood (FL), USA, FLL',
  'Fort McMurray, Canada, YMM',
  'Fort Myers, Metropolitan Area (FL), USA, FMY',
  'Fort Myers, Southwest Florida Reg (FL), USA, RSW',
  'Fort Riley (KS) - Marshall AAF, USA, FRI',
  'Fort Smith, Canada, YSM',
  'Fort Smith (AR), USA, FSM',
  'Fort St. John, Canada, YXJ',
  'Fort Walton Beach (FL), USA, VPS',
  'Fort Wayne (IN), USA, FWA',
  'Fort Worth (TX), USA, DFW',
  'Foula (Shetland), United Kingdom, FOU',
  'Francistown, Botswana, FRW',
  'Frankfurt/Main, Germany, FRA',
  'Frankfurt/Hahn, Germany, HHN',
  'Franklin/Oil City (PA), USA, FKL',
  'Fredericton, Canada, YFC',
  'Freeport, Bahamas, FPO',
  'Freetown, Sierra Leone, FNA',
  'Frejus, France, FRJ',
  'Fresno (CA), USA, FAT',
  'Friedrichshafen, Germany, FDH',
  'Fuerteventura, Spain, FUE',
  'Fujairah, United Arab Emirates, FJR',
  'Fukuoka, Japan, FUK',
  'Fukushima, Japan, FKS',
  'Funchal, Portugal, FNC',
  'Futuna, Wallis and Futuna Islands, FUT',
  'Gaborone, Botswana, GBE',
  'Gadsden (AL), USA, GAD',
  'Gainesville (FL), USA, GNV',
  'Galway, Ireland, GWY',
  'Gander, Canada, YQX',
  'Garoua, Cameroon, GOU',
  'Gaza City, Palestinian Territory, GZA',
  'Gaziantep, Turkey, GZT',
  'Gdansk, Poland, GDN',
  'Geelong, Australia, GEX',
  'Geneva, Switzerland, GVA',
  'Genoa, Italy, GOA',
  'George, South Africa, GRJ',
  'Georgetown, Guyana, GEO',
  'Geraldton, Australia, GET',
  'Gerona, Spain, GRO',
  'Ghent (Gent), Belgium, GNE',
  'Gibraltar, Gibraltar, GIB',
  'Gilette (WY), USA, GCC',
  'Gilgit, Pakistan, GIL',
  'Gillam, Canada, YGX',
  'Gladstone, Australia, GLT',
  'Glasgow, Prestwick, United Kingdom, PIK',
  'Glasgow, United Kingdom, GLA',
  'Glasgow (MT), USA, GGW',
  'Glendive (MT), USA, GDV',
  'Goa, India, GOI',
  'Goiania, Brazil, GYN',
  'Gold Coast, Australia, OOL',
  'Goondiwindi, Australia, GOO',
  'Goose Bay, Canada, YYR',
  'Gorna, Bulgaria, GOZ',
  'Gothenburg (Göteborg), Sweden, GOT',
  'Gove (Nhulunbuy), Australia, GOV',
  'Govenors Harbour, Bahamas, GHB',
  'Granada, Spain, GRX',
  'Grand Bahama International, Bahamas, FPO',
  'Grand Canyon (AZ), USA, GCN',
  'Grand Cayman - Owen Roberts International, Cayman Islands, GCM',
  'Grand Forks (ND), USA, GFK',
  'Grand Junction (CO), USA, GJT',
  'Grand Rapids (MI), USA, GRR',
  'Grand Rapids (MN), USA, GPZ',
  'Graz, Austria, GRZ',
  'Great Falls (MT), USA, GTF',
  'Great Keppel Island, Australia, GKL',
  'Green Bay (WI), USA, GRB',
  'Greenbrier/Lewisburg (WV), USA, LWB',
  'Greensboro/Winston Salem (NC), USA, GSO',
  'Greenville (MS), USA, GLH',
  'Greenville (NC), USA, PGV',
  'Greenville/Spartanburg (SC), USA, GSP',
  'Grenada, Grenada, GND',
  'Grenoble, France, GNB',
  'Griffith, Australia, GFF',
  'Groningen - Eelde, Netherlands, GRQ',
  'Groote Eylandt - Alyangula, Australia, GTE',
  'Groton/New London (CT), USA, GON',
  'Guadalajara, Mexico, GDL',
  'Guadalcanal, Solomon Islands, GSI',
  'Guam, Guam, GUM',
  'Guangzhou (Canton), Guangdong, PR China, CAN',
  'Sao Paulo , Brazil, GRU',
  'Guatemala City, Guatemala, GUA',
  'Guayaquil, Ecuador, GYE',
  'Guernsey, Channel Islands, GCI',
  'Guettin, Germany, GTI',
  'Gulfport/Biloxi (MS), USA, GPT',
  'Guilin - Liangjiang, Guangxi, PR China, KWL',
  'Gulu, Uganda, ULU',
  'Gunnison/Crested Butte (CO), USA, GUC',
  'Guwahati, India, GAU',
  'Gwadar, Pakistan, GWD',
  'Gweru, Zimbabwe, GWE',
  'Gympie, Australia, GYP',
  'Hachijo Jima, Japan, HAC',
  'Hagåtña, Guam, GUM',
  'Haifa, Israel, HFA',
  'Haines (AK), USA, HNS',
  'Hakodate, Japan, HKD',
  'Halifax International, Canada, YHZ',
  'Hall Beach, Canada, YUX',
  'Hamburg - Fuhlsbuettel, Germany, HAM',
  'Hamilton, Australia, HLT',
  'Hamilton, Canada, YHM',
  'Hamilton, New Zealand, HLZ',
  'Hamilton Island, Australia, HTI',
  'Hammerfest, Norway, HFT',
  'Hancock (MI), USA, CMX',
  'Hangchow (Hangzhou), Zhejiang, PR China, HGH',
  'Hannover, Germany, HAJ',
  'Hanoi, Vietnam, HAN',
  'Harare, Zimbabwe, HRE',
  'Harbin (Haerbin), Heilongjiang, PR China, HRB',
  'Harlingen/South Padre Island (TX), USA, HRL',
  'Harrington Harbour, PQ, Canada, YHR',
  'Harrisburg (PA) - Harrisburg Skyport, USA, HAR',
  'Harrisburg (PA) - Harrisburg International, USA, MDT',
  'Hartford (CT) /Springfield (MA), USA, BDL',
  'Hatyai (Hat Yai), Thailand, HDY',
  'Haugesund, Norway, HAU',
  'Havana, Cuba, HAV',
  'Havre (MT), USA, HVR',
  'Hayman Island, Australia, HIS',
  'Helena (MT), USA, HLN',
  'Helsingborg, Sweden, JHE',
  'Helsinki - Vantaa, Finland, HEL',
  'Heraklion, Greece, HER',
  'Hermosillo - Gen. Pesqueira Garcia, Mexico, HMO',
  'Hervey Bay, Australia, HVB',
  'Hibbing (MN), USA, HIB',
  'Hickory (NC), USA, HKY',
  'Hilo (HI), USA, ITO',
  'Hilton Head Island (SC), USA, HHH',
  'Hinchinbrook Island, Australia, HNK',
  'Hiroshima International, Japan, HIJ',
  'Ho Chi Minh City (Saigon), Viet Nam, SGN',
  'Hobart, Australia, HBA',
  'Hof, Germany, HOQ',
  'Holguin, Cuba, HOG',
  'Home Hill, Australia, HMH',
  'Homer (AK), USA, HOM',
  'Hong Kong - International Airport (HKIA), Hong Kong, HKG',
  'Hong Kong - Chek Lap Kok, Hong Kong, ZJK',
  'Honiara Henderson International, Solomon Islands, HIR',
  'Honolulu (HI), USA, HNL',
  'Hoonah (AK), USA, HNH',
  'Horta, Portugal, HOR',
  'Houston (TX) , Hobby, USA, HOU',
  'Houston, TX - George Bush Intercontinental Airport, USA, IAH',
  'Huahine, French Polynesia, HUH',
  'Huatulco, Mexico, HUX',
  'Hue - Phu Bai, Viet Nam, HUI',
  'Humberside, United Kingdom, HUY',
  'Huntington (WV), USA, HTS',
  'Huntsville (AL), USA, HSV',
  'Hurghada International, Egypt, HRG',
  'Huron (SD), USA, HON',
  'Hwange National Park, Zimbabwe, HWN',
  'Hyannis (MA), USA, HYA',
  'Hydaburg (AK), USA, HYG',
  'Hyderabad, India, HYD',
  'Hyderabad, Pakistan, HDD',
  'Ibiza, Ibiza/Spain, IBZ',
  'Idaho Falls (ID), USA, IDA',
  'Iguazu, Cataratas, Argentina, IGR',
  'Ile des Pins, New Caledonia, ILP',
  'Ile Ouen, New Caledonia, IOU',
  'Iliamna (AK), USA, ILI',
  'Imperial (CA), USA, IPL',
  'Incercargill, New Zealand, IVC',
  'Incheon, Korea South, ICN',
  'Indianapolis (IN) International, USA, IND',
  'Ingham, Australia, IGH',
  'Innisfail, Australia, IFL',
  'Innsbruck - Kranebitten, Austria, INN',
  'International Falls (MN), USA, INL',
  'Inuvik, Canada, YEV',
  'Invercargill, New Zealand, IVC',
  'Inverness, United Kingdom, INV',
  'Inykern (CA), USA, IYK',
  'Iqaluit (Frobisher Bay), Canada, YFB',
  'Iquitos, Peru, IQT',
  'Irkutsk, Russia, IKT',
  'Ishigaki, Japan, ISG',
  'Islamabad, Pakistan, ISB',
  'Islay, United Kingdom, ILY',
  'Isle of Man, , IOM',
  'Istanbul - Istanbul Atatürk Airport, Turkey, IST',
  'Istanbul - Sabiha Gokcen, Turkey, SAW',
  'Ithaca/Cortland (NY), USA, ITH',
  'Ivalo, Finland, IVL',
  'Ixtapa/Zihuatenejo, Mexico, ZIH',
  'Izmir, Turkey, IZM',
  'Izmir - Adnan Menderes Airport, Turkey, ADB',
  'Jackson Hole (WY), USA, JAC',
  'Jackson (MI) - Reynolds Municipal, USA, JXN',
  'Jackson,  MN  , USA, MJQ',
  'Jackson (MS) - Jackson Internationall, USA, JAN',
  'Jackson (MS) - Hawkins Field   , USA, HKS',
  'Jackson (TN) - Mckellar, USA, MKL',
  'Jackson Hole (WY), USA, JAC',
  'Jacksonville (AR)  Little Rock AFB   , USA, LRF',
  'Jacksonville (FL) - Cecil Field NAS   , USA, NZC',
  'Jacksonville (FL) Jacksonville NAS   , USA, NIP',
  'Jacksonville (FL) - International, USA, JAX',
  'Jacksonville (FL) - Craig Municipal   , USA, CRG',
  'Jacksonville (IL) - Municipal Airport, USA, IJX',
  'Jacksonville (NC), USA, OAJ',
  'Jacksonville (TX), USA, JKV',
  'Jacmel   , Haiti, JAK',
  'Jacobabad, Pakistan, JAG',
  'Jacobina   , Brazil, JCM',
  'Jacquinot Bay, Papua New Guinea, JAQ',
  'Jaffna - Kankesanturai, Sri Lanka, JAF',
  'Jagdalpur, India, JGB',
  'Jaipur - Sanganeer, India, JAI',
  'Jaisalmer   , India, JSA',
  'Jakarta - Halim Perdana Kusuma, Indonesia, HLP',
  'Jakarta - Metropolitan Area, Indonesia, JKT',
  'Jakarta - Soekarno-Hatta International, Indonesia, CGK',
  'Jalalabad    , Afghanistan, JAA',
  'Jalandhar, India, JLR',
  'Jalapa, Mexico, JAL',
  'Jales, Brazil, JLS',
  'Jaluit Island  , Marshall Islands, UIT',
  'Jamba, Angola, JMB',
  'Jambi - Sultan Taha Syarifudn, Indonesia , DJB',
  'Jambol, Bulgaria, JAM',
  'Jamestown (ND), USA, JMS',
  'Jamestown (NY), USA, JHW',
  'Jammu - Satwari, India, IXJ',
  'Jamnagar - Govardhanpur, India, JGA',
  'Jamshedpur, India, IXW',
  'Janakpur, Nepal, JKR',
  'Jandakot, Australia, JAD',
  'Janesville (WI) - Rock County, USA, JVL',
  'Januaria, Brazil, JNA',
  'Jaque   , Panama, JQE',
  'Jatai, Brazil, JTI',
  'Jauja, Peru, JAU',
  'Jayapura - Sentani, Indonesia, DJJ',
  'Jeddah, Saudi Arabia, JED',
  'Jefferson City (MO) - Jefferson Memorial, USA, JEF',
  'Jeremie, Haiti, JEE',
  'Jerez de la Frontera/Cadiz - La Parra, Spain, XRY',
  'Jersey, Channel Islands, JER',
  'Jerusalem, Israel, JRS',
  'Jessore, Bangladesh, JSR',
  'Jeypore, India, PYB',
  'Ji\'an, Jiangxi, China, JGS',
  'Jiamusi, PR China, JMU',
  'Jiayuguan, PR China, JGN',
  'Jijel, Algeria, GJL',
  'Jijiga, Ethiopia, JIJ',
  'Jilin, PR China, JIL',
  'Jimma, Ethiopia, JIM',
  'Jinan, Shandong, PR China, TNA',
  'Jingdezhen, PR China, JDZ',
  'Jinghong, PR China, JHG',
  'Jining, PR China, JNG',
  'Jinja, Uganda, JIN',
  'Jinjiang, PR China, JJN',
  'Jinka, Ethiopia, BCO',
  'Jinzhou, PR China, JNZ',
  'Jipijapa, Ecuador, JIP',
  'Jiri, Nepal, JIR',
  'Jiujiang, PR China, JIU',
  'Jiwani, Pakistan, JIW',
  'Joacaba, Brazil, JCB',
  'Joao Pessoa, Brazil, JPA',
  'Jodhpur, India, JDH',
  'Jönköping (Jonkoping), Sweden, JKG',
  'Joensuu, Finland, JOE',
  'Johannesburg, South Africa, JNB',
  'Johnson City (NY) - Binghamton/Endicott/Johnson, USA, BGM',
  'Johnston Island, USA, JON',
  'Johnstown (PA), USA, JST',
  'Johor Bahru, Malaysia, JHB',
  'Joinville, Brazil, JOI',
  'Jolo, Philippines, JOL',
  'Jomsom, Nepal, JMO',
  'Jonesboro (AR), USA, JBR',
  'Joplin (MO), USA, JLN',
  'Jorhat, India, JRH',
  'Jos, Nigeria, JOS',
  'Jose De San Martin, Argentina, JSM',
  'Jouf, Saudi Arabia, AJF',
  'Juanjui, Peru, JJI',
  'Juba, South Sudan, JUB',
  'Juist (island), Germany, JUI',
  'Juiz De Fora, Brazil, JDF',
  'Jujuy, Argentina, JUJ',
  'Julia Creek, Australia, JCK',
  'Juliaca, Peru, JUL',
  'Jumla, Nepal, JUM',
  'Jundah, Australia, JUN',
  'Juneau (AK), USA, JNU',
  'Junin, Argentina, JNI',
  'Juticalpa, Honduras, JUT',
  'Jwaneng, Botswana, JWA',
  'Jyväskylä (Jyvaskyla), Finland, JYV',
  'Kabul, Afghanistan, KBL',
  'Kagoshima, Japan, KOJ',
  'Kahramanmaras, Turkey, KCM',
  'Kahului (HI), USA, OGG',
  'Kajaani, Finland, KAJ',
  'Kalamata, Greece, KLX',
  'Kalamazoo/Battle Creek (MI), USA, AZO',
  'Kalgoorlie, Australia, KGI',
  'Kaliningrad, Russia, KGD',
  'Kalispell (MT), USA, FCA',
  'Kalmar, Sweden, KLR',
  'Kamloops, BC, Canada, YKA',
  'Kamuela (HI), USA, MUE',
  'Kano, Nigeria, KAN',
  'Kanpur, India, KNU',
  'Kansas City (MO), USA, MCI',
  'Kaohsiung International, Taiwan, KHH',
  'Kapalua West (HI), USA, JHM',
  'Karachi, Pakistan, KHI',
  'Karlsruhe-Baden - Soellingen, Germany, FKB',
  'Karlstad, Sweden, KSD',
  'Karpathos, Greece, AOK',
  'Karratha, Australia, KTA',
  'Kars, Turkey, KYS',
  'Karumba, Australia, KRB',
  'Karup, Denmark, KRP',
  'Kaschechawan, PQ, Canada, ZKE',
  'Kassala, Sudan, KSL',
  'Katherine, Australia, KTR',
  'Kathmandu, Nepal, KTM',
  'Katima Mulilo/Mpacha, Namibia, MPA',
  'Kauhajoki, Finland, KHJ',
  'Kaunakakai (HI), USA, MKK',
  'Kavalla, Greece, KVA',
  'Kayseri, Turkey, ASR',
  'Kazan, Russia, KZN',
  'Keetmanshoop, Namibia, KMP',
  'Kelowna, BC, Canada, YLW',
  'Kemi/Tornio, Finland, KEM',
  'Kenai (AK), USA, ENA',
  'Kent (Manston), United Kingdom, MSE',
  'Kerry County, Ireland, KIR',
  'Ketchikan (AK), USA, KTN',
  'Key West (FL), USA, EYW',
  'Khamis Mushayat, Saudi Arabia, AHB',
  'Kharga - New Valley, Egypt, UVL',
  'Kharkov, Ukraine, HRK',
  'Khartoum, Sudan, KRT',
  'Khuzdar, Pakistan, KDD',
  'Kiel - Holtenau, Germany, KEL',
  'Kiev - Borispol, Ukraine, KBP',
  'Kiev - Zhulhany, Ukraine, IEV',
  'Kigali - Gregoire Kayibanda, Rwanda, KGL',
  'Kilimadjaro, Tanzania, JRO',
  'Killeem (TX), USA, ILE',
  'Kimberley, South Africa, KIM',
  'King Island, King Island (Australia), KNS',
  'King Salomon (AK), USA, AKN',
  'Kingscote, Australia, KGC',
  'Kingston - Norman Manley, Jamaica, KIN',
  'Kingston (NC), USA, ISO',
  'Kingstown, Saint Vincent and the Grenadines, SVD',
  'Kinshasa - N\'Djili, Congo (DRC), FIH',
  'Kiritimati (island), Kiribati, CXI',
  'Kirkenes, Norway, KKN',
  'Kirkuk, Iraq, KIK',
  'Kirkwall (Orkney), United Kingdom, KOI',
  'Kiruna, Sweden, KRN',
  'Kisangani, Congo (DRC), FKI',
  'Kittilä, Finland, KTT',
  'Kitwe, Zambia, KIW',
  'Klagenfurt, Austria, KLU',
  'Klamath Fall (OR), USA, LMT',
  'Klawock (AK), USA, KLW',
  'Kleinsee, South Africa, KLZ',
  'Knock, Ireland, NOC',
  'Knoxville (TN), USA, TYS',
  'Kobe, Japan, UKB',
  'Kochi, Japan, KCZ',
  'Köln, Köln/Bonn, Germany, CGN',
  'Kodiak (AK), USA, ADQ',
  'Kohat, Pakistan, OHT',
  'Kokkola/Pietarsaari, Finland, KOK',
  'Kolkata (Calcutta) - Netaji Subhas Chandra, India, CCU',
  'Komatsu, Japan, KMQ',
  'Kona (HI), USA, KOA',
  'Konya, Turkey, KYA',
  'Korhogo, Cote d\'Ivoire, HGO',
  'Kos, Greece, KGS',
  'Kota Kinabalu, Malaysia, BKI',
  'Kotzbue (AK), USA, OTZ',
  'Kowanyama, Australia, KWM',
  'Krakow (Cracow), Poland, KRK',
  'Kristiansand, Norway, KRS',
  'Kristianstad, Sweden, KID',
  'Kristiansund, Norway, KSU',
  'Kuala Lumpur - International Airport, Malaysia, KUL',
  'Kuala Lumpur - Sultan Abdul Aziz Shah, Malaysia, SZB',
  'Kuantan, Malaysia, KUA',
  'Kuching, Malaysia, KCH',
  'Kumamoto, Japan, KMJ',
  'Kununurra, Australia, KNX',
  'Kuopio, Finland, KUO',
  'Kushiro, Japan, KUH',
  'Kuujjuaq (FortChimo), Canada, YVP',
  'Kuujjuarapik, Canada, YGW',
  'Kuusamo, Finland, KAO',
  'Kuwait, Kuwait, KWI',
  'Kyoto, Japan, UKY',
  'Labe, Guinea, LEK',
  'Labouchere Bay (AK), USA, WLB',
  'Labuan, Malaysia, LBU',
  'Lac Brochet, MB, Canada, XLB',
  'La Coruna, Spain, LCG',
  'La Crosse (WI), USA, LSE',
  'Lae, Papua New Guinea, LAE',
  'La Rochelle, France, LRH',
  'Lafayette (IN), USA, LAF',
  'Lafayette, La, USA, LFT',
  'Lagos, Nigeria, LOS',
  'La Grande, Canada, YGL',
  'Lahore, Pakistan, LHE',
  'Lake Charles (LA), USA, LCH',
  'Lake Havasu City (AZ), USA, HII',
  'Lake Tahoe (CA), USA, TVL',
  'Lakselv, Norway, LKL',
  'Lambarene, Gabon, LBQ',
  'Lamezia Terme, Italy, SUF',
  'Lampedusa, Italy, LMP',
  'Lanai City (HI), USA, LNY',
  'Lancaster (PA), USA, LNS',
  'Land\'s End, United Kingdom, LEQ',
  'Langkawi (islands), Malaysia, LGK',
  'Lannion, France, LAI',
  'Lanseria, South Africa, HLA',
  'Lansing (MI), USA, LAN',
  'La Paz - El Alto, Bolivia, LPB',
  'La Paz - Leon, Mexico, LAP',
  'Lappeenranta, Finland, LPP',
  'Laramie (WY), USA, LAR',
  'Laredo (TX), USA, LRD',
  'Larnaca, Cyprus, LCA',
  'Las Palmas, Spain, LPA',
  'Las Vegas (NV), USA, LAS',
  'Latrobe (PA), USA, LBE',
  'Launceston, Australia, LST',
  'Laurel/Hattisburg (MS), USA, PIB',
  'Laverton, Australia, LVO',
  'Lawton (OK), USA, LAW',
  'Lazaro Cardenas, Mexico, LZC',
  'Leaf Rapids, Canada, YLR',
  'Learmouth (Exmouth), Australia, LEA',
  'Lebanon (NH), USA, LEB',
  'Leeds/Bradford, United Kingdom, LBA',
  'Leinster, Australia, LER',
  'Leipzig, Germany, LEJ',
  'Lelystad, Netherlands, LEY',
  'Leon, Mexico, BJX',
  'Leonora, Australia, LNO',
  'Lerwick/Tingwall (Shetland Islands), United Kingdom, LWK',
  'Lewiston (ID), USA, LWS',
  'Lewistown (MT), USA, LWT',
  'Lexington (KY), USA, LEX',
  'Libreville, Gabon, LBV',
  'Lidkoeping, Sweden, LDK',
  'Liege, Belgium, LGG',
  'Lifou, Loyaute, Pazifik, LIF',
  'Lihue (HI), USA, LIH',
  'Lille , France, LIL',
  'Lilongwe, Malawi, LLW',
  'Lima, Peru, LIM',
  'Limassol, Cyprus, QLI',
  'Limoges, France, LIG',
  'Lincoln (NE), USA, LNK',
  'Lindeman Island, Australia, LDC',
  'Linz - Hoersching, Austria, LNZ',
  'Lisala, Congo (DRC), LIQ',
  'Lisbon - Lisboa, Portugal, LIS',
  'Lismore, Australia, LSY',
  'Little Rock (AR), USA, LIT',
  'Liverpool, United Kingdom, LPL',
  'Lizard Island, Australia, LZR',
  'Ljubljana - Brnik, Slovenia, LJU',
  'Lockhart River, Australia, IRG',
  'Lome, Togo, LFW',
  'London, Canada, YXU',
  'London Metropolitan Area, United Kingdom, LON',
  'London - City Airport, United Kingdom, LCY',
  'London - Gatwick, United Kingdom, LGW',
  'London - Heathrow, United Kingdom, LHR',
  'London - Luton, United Kingdom, LTN',
  'London - Stansted, United Kingdom, STN',
  'Londonderry - Eglinton, United Kingdom, LDY',
  'Long Beach (CA), USA, LGB',
  'Long Island (AK), USA, LIJ',
  'Long Island, Islip (NY) - Mac Arthur, USA, ISP',
  'Longreach, Australia, LRE',
  'Longview/Kilgore (TX), USA, GGG',
  'Longyearbyen - Svalbard, Svalbard/Norway, LYR',
  'Loreto, Mexico, LTO',
  'Lorient, France, LRT',
  'Los Angeles (CA), USA, LAX',
  'Los Cabos, Mexico, SJD',
  'Los Mochis, Mexico, LMM',
  'Los Rodeos, Teneriffa/Spain, TFN',
  'Losinj - Losinj Arpt, Croatia (Hrvatska), LSZ',
  'Lourdes/Tarbes, France, LDE',
  'Louisville (KY), USA, SDF',
  'Luanda - 4 de Fevereiro, Angola, LAD',
  'Lubbock (TX), USA, LBB',
  'Lucknow, India, LKO',
  'Luederitz, Namibia, LUD',
  'Luga, Malta, MLA',
  'Lugano, Switzerland, LUG',
  'Lulea, Sweden, LLA',
  'Lumbumbashi, Congo (DRC), FBM',
  'Lusaka, Zambia, LUN',
  'Lusisiki, South Africa, LUJ',
  'Luxembourg, Luxembourg, LUX',
  'Luxi - Mangshi, Yunnan, PR China, LUM',
  'Luxor, Egypt, LXR',
  'Lvov (Lwow, Lemberg), Ukraine, LWO',
  'Lydd, United Kingdom, LYX',
  'Lynchburg (VA), USA, LYH',
  'Lyon , France, LYS',
  'Lyons (KS) - Rice County Municipal, USA, LYO',
  'Maastricht/Aachen, Netherlands, MST',
  'Macapa, Brazil, MCP',
  'Macau, Macau, China SAR, MFM',
  'Maceio, Brazil, MCZ',
  'Mackay, Australia, MKY',
  'Macon (GA), USA, MCN',
  'Mactan Island - Nab, Philippines, NOP',
  'Madinah (Medina) - Mohammad Bin Abdulaziz, Saudi Arabia, MED',
  'Madison (WI), USA, MSN',
  'Madras (Chennai), India, MAA',
  'Madrid, Spain, MAD',
  'Mahe, Seychelles, SEZ',
  'Mahon, Spain, MAH',
  'Maitland, Australia, MTL',
  'Majunga, Madagascar, MJN',
  'Makung, Taiwan, MZG',
  'Malabo , Equatorial Guinea, SSG',
  'Malaga, Spain, AGP',
  'Malatya, Turkey, MLX',
  'Male, Maledives, MLE',
  'Malindi, Kenya, MYD',
  'Malmo (Malmoe), Sweden, MMA',
  'Malmo (Malmö) - Malmö Airport, Sweden, MMX',
  'Man, Cote d\'Ivoire, MJC',
  'Managua - Augusto C Sandino, Nicaragua, MGA',
  'Manaus, Brazil, MAO',
  'Manchester, United Kingdom, MAN',
  'Manchester (NH), USA, MHT',
  'Mandalay , Myanmar, MDL',
  'Manguna, Papua New Guinea, MFO',
  'Manihi, French Polynesia, XMH',
  'Manila, Philippines, MNL',
  'Manzanillo, Mexico, ZLO',
  'Manzini, Swaziland, MTS',
  'Maputo, Mozambique, MPM',
  'Mar del Plata, Argentina, MDQ',
  'Maracaibo, Venezuela, MAR',
  'Maradi, Niger, MFQ',
  'Maras, Turkey, KCM',
  'Marathon (FL), USA, MTH',
  'Mardin, Turkey, MQM',
  'Mare, New Caledonia, MEE',
  'Margate, South Africa, MGH',
  'Margerita, Venezuela, PMV',
  'Maribor, Slovenia, MBX',
  'Mariehamn (Maarianhamina), Finland, MHQ',
  'Maroua, Cameroon, MVR',
  'Marquette (MI), USA, MQT',
  'Marrakesh, Morocco, RAK',
  'Marsa Alam, Egypt, RMF',
  'Marsa Matrah (Marsa Matruh), Egypt, MUH',
  'Marseille, France, MRS',
  'Marsh Harbour, Bahamas, MHH',
  'Martha\'s Vineyard (MA), USA, MVY',
  'Martinsburg (WV), USA, MRB',
  'Maryborough, Australia, MBH',
  'Maseru, Lesotho, MSU',
  'Mason City IA, USA, MCW',
  'Masvingo, Zimbabwe, MVZ',
  'Matsumoto, Nagano, Japan, MMJ',
  'Matsuyama, Japan, MYJ',
  'Mattoon (IL), USA, MTO',
  'Maun, Botswana, MUB',
  'Maupiti, French Polynesia, MAU',
  'Mauritius, Mauritius, MRU',
  'Mayaguez, Puerto Rico, MAZ',
  'Mazatlan, Mexico, MZT',
  'McAllen (TX), USA, MFE',
  'Medan, Indonesia, MES',
  'Medan - Kualanamu International, Indonesia, KNO',
  'Medellin, Colombia, MDE',
  'Medford (OR), USA, MFR',
  'Medina, Saudi Arabia, MED',
  'Meekatharra, Australia, MKR',
  'Melbourne, Australia, MEL',
  'Melbourne (FL), USA, MLB',
  'Melville Hall, Dominica, DOM',
  'Memphis (TN), USA, MEM',
  'Mendoza, Argentina, MDZ',
  'Manado, Indonesia, MDC',
  'Merced (CA), USA, MCE',
  'Merida, Mexico, MID',
  'Meridian (MS), USA, MEI',
  'Merimbula, Australia, MIM',
  'Messina, South Africa, MEZ',
  'Metlakatla (AK), USA, MTM',
  'Metz -  Frescaty, France, MZM',
  'Metz/Nancy Metz-Nancy-Lorraine, France, ETZ',
  'Mexicali, Mexico, MXL',
  'Mexico City - Mexico City International Airport, Mexico, MEX',
  'Mexico City - Atizapan, Mexico, AZP',
  'Mexico City - Juarez International, Mexico, MEX',
  'Mexico City - Santa Lucia, Mexico, NLU',
  'Mfuwe, Zambia, MFU',
  'Miami (FL), USA, MIA',
  'Mianwali, Pakistan, MWD',
  'Middlemount, Australia, MMM',
  'Midland/Odessa (TX), USA, MAF',
  'Midway Island - Sand Island Field, US Minor Outlying Islands, MDY',
  'Mikkeli, Finland, MIK',
  'Milan, Italy, MIL',
  'Milan - Linate, Italy, LIN',
  'Milan - Malpensa, Italy, MXP',
  'Milan - Orio Al Serio, Italy, BGY',
  'Mildura, Australia, MQL',
  'Miles City (MT), USA, MLS',
  'Milford Sound, New Zealand, MFN',
  'Milwaukee (WI), USA, MKE',
  'Minatitlan, Mexico, MTT',
  'Mineralnye Vody, Russia, MRV',
  'Minneapolis (MN), USA, MSP',
  'Minot (ND), USA, MOT',
  'Minsk, International, Belarus, MSQ',
  'Miri, Malaysia, MYY',
  'Mirpur, Pakistan, QML',
  'Missula (MT), USA, MSO',
  'Mitchell (SD), USA, MHE',
  'Miyako Jima (Ryuku Islands) - Hirara, Japan, MMY',
  'Miyazaki, Japan, KMI',
  'Mkambati, South Africa, MBM',
  'Moanda, Gabon, MFF',
  'Mobile (AL) - Pascagoula (MS), USA, MOB',
  'Modesto (CA), USA, MOD',
  'Moenjodaro, Pakistan, MJD',
  'Mogadishu, Somalia, MGQ',
  'Mokuti, Namibia, OKU',
  'Moline/Quad Cities (IL), USA, MLI',
  'Mombasa, Kenya, MBA',
  'Monastir, Tunisia, MIR',
  'Moncton, Canada, YQM',
  'Monroe (LA), USA, MLU',
  'Monrovia - Metropolitan Area, Liberia, MLW',
  'Monrovia - Roberts International, Liberia, ROB',
  'Montego Bay, Jamaica, MBJ',
  'Montenegro, Brazil, QGF',
  'Monterey (CA), USA, MRY',
  'Monterrey - Gen. Mariano Escobedo, Mexico, MTY',
  'Monterrey - Aeropuerto Del Norte, Mexico, NTR',
  'Montevideo , Uruguay, MVD',
  'Montgomery (AL), USA, MGM',
  'Montpellier, France, MPL',
  'Montreal, Canada, YMQ',
  'Montreal - Dorval (Montréal-Trudeau), Canada, YUL',
  'Montreal - Mirabel, Canada, YMX',
  'Montrose/Tellruide (CO), USA, MTJ',
  'Moorea, French Polynesia, MOZ',
  'Moranbah, Australia, MOV',
  'Moree, Australia, MRZ',
  'Morelia, Mexico, MLM',
  'Morgantown (WV), USA, MGW',
  'Morioka, Hanamaki, Japan, HNA',
  'Moroni - Prince Said Ibrahim, Comoros (Comores), HAH',
  'Moruya, Australia, MYA',
  'Moscow - Metropolitan Area, Russia, MOW',
  'Moscow - Domodedovo, Russia, DME',
  'Moscow - Sheremetyevo, Russia, SVO',
  'Moscow - Vnukovo, Russia, VKO',
  'Moses Lake (WA), USA, MWH',
  'Mossel Bay, South Africa, MZY',
  'Mostar, Bosnia and Herzegovina, OMO',
  'Mosul, Iraq, OSM',
  'Mouila, Gabon, MJL',
  'Moundou, Chad, MQQ',
  'Mount Cook, New Zealand, GTN',
  'Mount Gambier, Australia, MGB',
  'Mount Magnet, Australia, MMG',
  'Mt. Isa, Australia, ISA',
  'Mt. McKinley (AK), USA, MCL',
  'Muenchen (Munich) - Franz Josef Strauss, Germany, MUC',
  'Muenster/Osnabrueck, Germany, FMO',
  'Mulhouse, France, MLH',
  'Multan, Pakistan, MUX',
  'Murcia, Spain, MJV',
  'Murmansk, Russia, MMK',
  'Mus, Turkey, MSR',
  'Muscat - Seeb, Oman, MCT',
  'Muscle Shoals (AL), USA, MSL',
  'Muskegon (MI), USA, MKG',
  'Muzaffarabad, Pakistan, MFG',
  'Mvengue, Gabon, MVB',
  'Mykonos, Greece, JMK',
  'Myrtle Beach (SC) - Myrtle Beach AFB, USA, MYR',
  'Myrtle Beach (SC) - Grand Strand Airport, USA, CRE',
  'Mysore, India, MYQ',
  'Mytilene (Lesbos), Greece, MJT',
  'Mzamba, South Africa, MZF',
  'Nadi, Fiji, NAN',
  'Nagasaki, Japan, NGS',
  'Nagoya - Komaki AFB, Japan, NGO',
  'Nagpur, India, NAG',
  'Nairobi, Kenya, NBO',
  'Nakhichevan, Azerbaijan, NAJ',
  'Nakhon Si Thammarat, Thailand, NST',
  'Nancy, France, ENC',
  'Nanisivik, Canada, YSR',
  'Nanning, Guangxi, PR China, NNG',
  'Nantes, France, NTE',
  'Nantucket (MA), USA, ACK',
  'Naples, Italy, NAP',
  'Naples (FL), USA, APF',
  'Narrabri, Australia, NAA',
  'Narrandera, Australia, NRA',
  'Narsarsuaq, Greenland, UAK',
  'Nashville (TN), USA, BNA',
  'Nassau, Bahamas, NAS',
  'Natal, Brazil, NAT',
  'Nausori, Fiji/Suva, SUV',
  'Nawab Shah, Pakistan, WNS',
  'Naxos, Greece, JNX',
  'N\'Djamena, Chad, NDJ',
  'N\'Dola, Zambia, NLA',
  'Nelson, New Zealand, NSN',
  'Nelspruit, South Africa, NLP',
  'Nelspruit, South Africa, MQP',
  'Nevis, St. Kitts and Nevis, NEV',
  'New Bern (NC), USA, EWN',
  'New Haven (CT), USA, HVN',
  'New Orleans, La, USA, MSY',
  'Newquay, United Kingdom, NQY',
  'New Valley - Kharga, Egypt, UVL',
  'New York - John F. Kennedy (NY), USA, JFK',
  'New York - LaGuardia (NY), USA, LGA',
  'New York - Newark (NJ), USA, EWR',
  'New York (NY), USA, NYC',
  'Newburgh (NY), USA, SWF',
  'Newcastle - Belmont, Australia, BEO',
  'Newcastle - Williamtown, Australia, NTL',
  'Newcastle, United Kingdom, NCL',
  'Newcastle, South Africa, NCS',
  'Newman, Australia, ZNE',
  'Newport News/Williamsburg (VA), USA, PHF',
  'N\'Gaoundere, Cameroon, NGE',
  'Niagara Falls International, USA, IAG',
  'Niamey, Niger, NIM',
  'Nice, France, NCE',
  'Nicosia, Cyprus, NIC',
  'Nikolaev, Ukraine, NLV',
  'Niigata, Japan, KIJ',
  'Nimes, France, FNI',
  'Nis, Serbia, INI',
  'Nizhny Novgorod, Russia, GOJ',
  'Nome (AK), USA, OME',
  'Noosa, Australia, NSA',
  'Norfolk Island, Australia, NLK',
  'Norfolk/Virginia Beach (VA), USA, ORF',
  'Norman Wells, Canada, YVQ',
  'Norrkoeping, Sweden, NRK',
  'North Bend (OR), USA, OTH',
  'North Eleuthera, Bahamas, ELH',
  'Norwich, United Kingdom, NWI',
  'Nottingham - East Midlands, United Kingdom, EMA',
  'Nouadhibou, Mauritania, NDB',
  'Nouakchott, Mauritania, NKC',
  'Noumea, New Caledonia, NOU',
  'Novi Sad, Serbia, QND',
  'Novosibirsk, Russia, OVB',
  'Nürnberg (Nuremberg), Germany, NUE',
  'Nuevo Laredo, Mexico, NLD',
  'Nuku\'alofa, Tonga, TBU',
  'Oakland (CA), USA, OAK',
  'Oaxaca - Xoxocotlan, Mexico, OAX',
  'Odense, Denmark, ODE',
  'Odessa, Ukraine, ODS',
  'Oerebro, Sweden, ORB',
  'Ohrid, Macedonia, OHD',
  'Oita, Japan, OIT',
  'Okayama, Japan, OKJ',
  'Okinawa, Ryukyo Island - Naha, Japan, OKA',
  'Oklahoma City (OK) - Will Rogers World, USA, OKC',
  'Olbia, Italy, OLB',
  'Olympic Dam, Australia, OLP',
  'Omaha (NE), USA, OMA',
  'Ondangwa, Namibia, OND',
  'Ontario (CA), USA, ONT',
  'Oran (Ouahran), Algeria, ORN',
  'Orange, Australia, OAG',
  'Orange County (Santa Ana) (CA), USA, SNA',
  'Oranjemund, Namibia, OMD',
  'Oranjestad, Aruba, AUA',
  'Orkney - Kirkwall, United Kingdom, KOI',
  'Orlando Metropolitan Area (FL), USA, ORL',
  'Orlando - International Airport (FL), USA, MCO',
  'Orpheus Island, Australia, ORS',
  'Osaka, Metropolitan Area, Japan, OSA',
  'Osaka - Itami, Japan, ITM',
  'Osaka - Kansai International Airport, Japan, KIX',
  'Oshkosh (WI), USA, OSH',
  'Osijek, Croatia (Hrvatska), OSI',
  'Oslo - Oslo Airport, Gardermoen, Norway, OSL',
  'Oslo - Fornebu, Norway, FBU',
  'Oslo - Sandefjord, Norway, TRF',
  'Ottawa - Hull, Canada, YOW',
  'Ouadda, Central African Republic, ODA',
  'Ouarzazate, Morocco, OZZ',
  'Oudtshoorn, South Africa, OUH',
  'Ouagadougou, Burkina Faso, OUA',
  'Oujda, Morocco, OUD',
  'Oulu, Finland, OUL',
  'Out Skerries (Shetland), United Kingdom, OUK',
  'Oviedo, Spain, OVD',
  'Owensboro (KY), USA, OWB',
  'Oxnard (CA), USA, OXR',
  'Oyem, Gabon/Loyautte, UVE',
  'Paderborn/Lippstadt, Germany, PAD',
  'Paducah (KY), USA, PAH',
  'Page/Lake Powell (AZ), USA, PGA',
  'Pago Pago, American Samoa, PPG',
  'Pakersburg (WV) /Marietta (OH), USA, PKB',
  'Palermo - Punta Raisi, Italy, PMO',
  'Palma de Mallorca, Spain, PMI',
  'Palmas, Brazil, PMW',
  'Palmdale/Lancaster (CA), USA, PMD',
  'Palmerston North, New Zealand, PMR',
  'Palm Springs (CA), USA, PSP',
  'Panama City - Tocumen International, Panama, PTY',
  'Panama City (FL), USA, PFN',
  'Panjgur, Pakistan, PJG',
  'Pantelleria, Italy, PNL',
  'Papeete - Faaa, French Polynesia (Tahiti), PPT',
  'Paphos, Cyprus, PFO',
  'Paraburdoo, Australia, PBO',
  'Paramaribo, Suriname, PBM',
  'Paris, France, PAR',
  'Paris - Charles de Gaulle, France, CDG',
  'Paris - Le Bourget, France, LBG',
  'Paris - Orly, France, ORY',
  'Paro, Bhutan, PBH',
  'Pasco (WA), USA, PSC',
  'Pasni, Pakistan, PSI',
  'Patna, India, PAT',
  'Pattaya, Thailand, PYX',
  'Pau, France, PUF',
  'Pellston (MI), USA, PLN',
  'Penang International, Malaysia, PEN',
  'Pendelton (OR), USA, PDT',
  'Pensacola (FL), USA, PNS',
  'Peoria/Bloomington (IL), USA, PIA',
  'Pereira, Colombia, PEI',
  'Perpignan, France, PGF',
  'Perth International, Australia, PER',
  'Perugia, Italy, PEG',
  'Pescara, Italy, PSR',
  'Peshawar, Pakistan, PEW',
  'Petersburg (AK), USA, PSG',
  'Phalaborwa, South Africa, PHW',
  'Philadelphia (PA), USA, PHL',
  'Phnom Penh - Pochentong, Cambodia, PNH',
  'Phoenix (AZ), USA, PHX',
  'Phuket, Thailand, HKT',
  'Pierre (SD), USA, PIR',
  'Pietermaritzburg, South Africa, PZB',
  'Pietersburg, South Africa, PTG',
  'Pilanesberg/Sun City, South Africa, NTY',
  'Pisa - Galileo Galilei, Italy, PSA',
  'Pittsburgh International Airport (PA), USA, PIT',
  'Plattsburgh (NY), USA, PLB',
  'Plettenberg Bay, South Africa, PBZ',
  'Pocatello (ID), USA, PIH',
  'Podgorica, Montenegro, TGD',
  'Pohnpei, Micronesia, PNI',
  'Pointe a Pitre, Guadeloupe, PTP',
  'Pointe Noire, Congo (ROC), PNR',
  'Poitiers - Biard, France, PIS',
  'Ponce, Puerto Rico, PSE',
  'Ponta Delgada, Portugal, PDL',
  'Pori, Finland, POR',
  'Port Angeles (WA), USA, CLM',
  'Port au Prince, Haiti, PAP',
  'Port Augusta, Australia, PUG',
  'Port Elizabeth, South Africa, PLZ',
  'Port Gentil, Gabon, POG',
  'Port Harcourt, Nigeria, PHC',
  'Port Hedland, Australia, PHE',
  'Portland, Australia, PTJ',
  'Portland (ME), USA, PWM',
  'Portland International (OR), USA, PDX',
  'Port Lincoln, Australia, PLO',
  'Port Macquarie, Australia, PQQ',
  'Port Menier, PQ, Canada, YPN',
  'Port Moresby - Jackson Field, Papua New Guinea, POM',
  'Porto, Portugal, OPO',
  'Porto Alegre, Brazil, POA',
  'Port of Spain, Trinidad and Tobago, POS',
  'Port Said, Egypt, PSD',
  'Porto Santo, Portugal, PXO',
  'Porto Velho, Brazil, PVH',
  'Port Vila, Vanuatu, VLI',
  'Poughkeepsie (NY), USA, POU',
  'Poznan, Lawica, Poland, POZ',
  'Prague, Czech Republic, PRG',
  'Praia, Cape Verde, RAI',
  'Presque Island (ME), USA, PQI',
  'Pretoria - Wonderboom Apt., South Africa, PRY',
  'Preveza/Lefkas, Greece, PVK',
  'Prince George, Canada, YXS',
  'Prince Rupert/Digby Island, Canada, YPR',
  'Pristina, Serbia, PRN',
  'Prosperpine, Australia, PPP',
  'Providence (RI), USA, PVD',
  'Prudhoe Bay (AK), USA, SCC',
  'Puebla, Mexico, PBC',
  'Pueblo (CO), USA, PUB',
  'Puerto Escondido, Mexico, PXM',
  'Puerto Ordaz, Venezuela, PZO',
  'Puerto Plata, Dominican Republic, POP',
  'Puerto Vallarta, Mexico, PVR',
  'Pukatawagan, Canada, XPK',
  'Pula, Croatia (Hrvatska), PUY',
  'Pullman (WA), USA, PUW',
  'Pune, India, Maharashtra, PNQ',
  'Punta Arenas - Presidente Carlos Ibáñez del Campo, Chile, PUQ',
  'Punta Cana, Dominican Republic, PUJ',
  'Pu San (Busan), South Korea, PUS',
  'Pyongyang, North Korea, FNJ',
  'Quebec, Canada, YQB',
  'Queenstown, Australia, UEE',
  'Queenstown, New Zealand, ZQN',
  'Quetta, Pakistan, UET',
  'Qingdao, Shandong, PR China, TAO',
  'Quimper, France, UIP',
  'Quincy (IL), USA, UIN',
  'Quito, Ecuador, UIO',
  'Rabat , Morocco, RBA',
  'Rahim Yar Khan, Pakistan, RYK',
  'Raiatea, French Polynesia, RFP',
  'Rainbow Lake, AB, Canada, YOP',
  'Rajkot, India, RAJ',
  'Raleigh/Durham (NC), USA, RDU',
  'Ranchi, India, IXR',
  'Rangiroa, French Polynesia, RGI',
  'Rangoon (Yangon) - Mingaladon, Myanmar, RGN',
  'Rapid City (SD), USA, RAP',
  'Rarotonga, Cook Island, RAR',
  'Ras al Khaymah (Ras al Khaimah), United Arab Emirates, RKT',
  'Rawala Kot, Pakistan, RAZ',
  'Rawalpindi, Pakistan, RWP',
  'Reading (PA), USA, RDG',
  'Recife, Brazil, REC',
  'Redding (CA), USA, RDD',
  'Redmond (OR), USA, RDM',
  'Reggio Calabria, Italy, REG',
  'Regina, Canada, YQR',
  'Reina Sofia, Teneriffa/Spain, TFS',
  'Rennes, France, RNS',
  'Reno (NV), USA, RNO',
  'Resolute Bay, Canada, YRB',
  'Reus, Spain, REU',
  'Reykjavik - Metropolitan Area, Iceland, REK',
  'Reykjavik - Keflavik International, Iceland, KEF',
  'Rhinelander (WI), USA, RHI',
  'Rhodos, Greece, RHO',
  'Richards Bay, South Africa, RCB',
  'Richmond (VA), USA, RIC',
  'Riga, Latvia, RIX',
  'Rijeka, Croatia (Hrvatska), RJK',
  'Rimini, Italy, RMI',
  'Rio Branco, Brazil, RBR',
  'Rio de Janeiro - Galeao, Brazil, GIG',
  'Rio de Janeiro - Santos Dumont, Brazil, SDU',
  'Rio de Janeiro, Brazil, RIO',
  'Riyadh, Saudi Arabia, RUH',
  'Roanne, France, RNE',
  'Roanoke (VA), USA, ROA',
  'Roatan, Honduras, RTB',
  'Rochester (MN), USA, RST',
  'Rochester (NY), USA, ROC',
  'Rock Sound, Bahamas, RSD',
  'Rock Springs (WY), USA, RKS',
  'Rockford (IL), USA, RFD',
  'Rockhampton, Australia, ROK',
  'Rockland (ME), USA, RKD',
  'Rocky Mount - Wilson (NC), USA, RWI',
  'Rodez, France, RDZ',
  'Rodrigues Island, Mauritius, RRG',
  'Roenne, Denmark, RNN',
  'Rome, Italy, ROM',
  'Rome - Ciampino, Italy, CIA',
  'Rome - Fuimicino, Italy, FCO',
  'Ronneby, Sweden, RNB',
  'Rosario, Argentina, ROS',
  'Rostov-on-Don - Rostov-on-Don Airport, Russia, RVI',
  'Rostov-on-Don - Platov International Airport, Russia, ROV',
  'Rotorua, New Zealand, ROT',
  'Rotterdam, Netherlands, RTM',
  'Rovaniemi, Finland, RVN',
  'Rundu, Namibia, NDU',
  'Ruse, Bulgaria, ROU',
  'Saarbruecken, Germany, SCN',
  'Sacramento (CA), USA, SMF',
  'Sado Shima, Japan, SDS',
  'Saginaw/Bay City/Midland (MI), USA, MBS',
  'Saidu Sharif, Pakistan, SDT',
  'Saigon (Ho Chi Minh City), Viet Nam, SGN',
  'Saint Brieuc, France, SBK',
  'Saint Denis, Reunion, RUN',
  'Saint John, Canada, YSJ',
  'Saipan, Northern Mariana Islands, SPN',
  'Sal, Cape Verde, SID',
  'Salalah, Oman, SLL',
  'Salem (OR), USA, SLE',
  'Salinas (CA), USA, SNS',
  'Salinas, Ecuador, SNC',
  'Salisbury, Zimbabwe, SAY',
  'Salisbury (MD), USA, SBY',
  'Saloniki, Greece, SKG',
  'Salta, Gen Belgrano, Argentina, SLA',
  'Salt Lake City (UT), USA, SLC',
  'Salvador, Brazil, SSA',
  'Salzburg - W.A. Mozart, Austria, SZG',
  'Samara, Russia, KUF',
  'Samarkand, Uzbekistan, SKD',
  'Samos, Greece, SMI',
  'Samsun, Turkey, SZF',
  'San Andres, Colombia, ADZ',
  'San Angelo (TX), USA, SJT',
  'San Antonio (TX), USA, SAT',
  'San Carlos de Bariloche, Argentina, BRC',
  'San Diego (CA), USA, SAN',
  'San Francisco, SA, USA, SFO',
  'San Jose Cabo, Mexico, SJD',
  'San Jose, Costa Rica, SJO',
  'San Jose (CA), USA, SJC',
  'San Juan, Puerto Rico, SJU',
  'San Luis Obisco (CA), USA, SBP',
  'San Luis Potosi, Mexico, SLP',
  'San Pedro, Cote d\'Ivoire, SPY',
  'San Pedro Sula, Honduras, SAP',
  'San Salvador, Bahamas, ZSA',
  'San Salvador, El Salvador, SAL',
  'San Sebastian, Spain, EAS',
  'Sanaa (Sana\'a), Yemen, SAH',
  'Sandspit, Canada, YZP',
  'Santa Ana (CA), USA, SNA',
  'Santa Barbara (CA), USA, SBA',
  'Santa Cruz de la Palma, Spain, SPC',
  'Santa Cruz de la Sierra, Bolivia, SRZ',
  'Santa Katarina - Mount Sinai, Egypt, SKV',
  'Santa Maria, Portugal, SMA',
  'Santa Maria (CA), USA, SMX',
  'Santander, Spain, SDR',
  'Santa Rosa (CA), USA, STS',
  'Santa Rosa, Bolivia, SRB',
  'Santa Rosa, Brazil, SRA',
  'Santa Rosa, Argentina, RSA',
  'Santa Rosa, Copan, Honduras, SDH',
  'Santa Rosalia, Colombia, SSL',
  'Santa Rosalia, Mexico, SRL',
  'Santiago, Cuba, SCU',
  'Santiago de Chile - Arturo Merino Benitez, Chile, SCL',
  'Santiago de Compostela, Spain, SCQ',
  'Santo, Vanuatu, SON',
  'Santo Domingo, Dominican Republic, SDQ',
  'Sao Luis, Brazil, SLZ',
  'Sao Paulo, Brazil, SAO',
  'Sao Paulo - Congonhas, Brazil, CGH',
  'Sao Paulo - Guarulhos, Brazil, GRU',
  'Sao Paulo - Viracopos, Brazil, VCP',
  'Sao Tome, Sao Tome & Principe, TMS',
  'Sapporo, Hokkaido, Japan, SPK',
  'Sapporo - Okadama, Hokkaido, Japan, OKD',
  'Sapporo, Japan, CTS',
  'Sarajevo, Bosnia and Herzegovina, SJJ',
  'Saransk, Russia, SKX',
  'Sarasota/Bradenton (FL), USA, SRQ',
  'Saskatoon, Canada, YXE',
  'Sassandra, Cote d\'Ivoire, ZSS',
  'Savannah (GA), USA, SAV',
  'Savonlinna, Finland, SVL',
  'Scarborough, Trinidad and Tobago, TAB',
  'Scone, Australia, NSO',
  'Scottsdale (AZ), USA, SCF',
  'Seattle/Tacoma (WA), USA, SEA',
  'Sehba, Libya, SEB',
  'Seinaejoki, Finland, SJY',
  'Selibi Phikwe, Botswana, PKW',
  'Sendai, Japan, SDJ',
  'Seoul - Incheon International Airport, South Korea, ICN',
  'Seoul - Kimpo, South Korea, SEL',
  'Sevilla, Spain, SVQ',
  'Sfax, Tunisia, SFA',
  'Shamattawa, MB, Canada, ZTM',
  'Shanghai - Hongqiao, China, SHA',
  'Shanghai - Pu Dong, China, PVG',
  'Shannon (Limerick), Ireland, SNN',
  'Sharjah, United Arab Emirates, SHJ',
  'Sharm El Sheikh, Egypt, SSH',
  'Sheffield, City Airport, United Kingdom, SZD',
  'Sheffield, Doncaster, Robin Hood International Airport, United Kingdom, DSA',
  'Shenandoah Valley/Stauton (VA), USA, SHD',
  'Shenyang, Liaoning, PR China, SHE',
  'Shenzhen, Guangdong, PR China, SZX',
  'Sheridan (WY), USA, SHR',
  'Shreveport, La, USA, SHV',
  'Shute Harbour, Australia, JHQ',
  'Sibu, Malaysia, SBW',
  'Sidney (MT), USA, SDY',
  'Silistra, Bulgaria, SLS',
  'Simferopol, Ukraine, SIP',
  'Sindhri, Pakistan, MPD',
  'Singapore - Changi, Singapore, SIN',
  'Singapore - Paya Lebar, Singapore, QPG',
  'Singapore - Seletar, Singapore, XSP',
  'Singleton, Australia, SIX',
  'Sioux City IA, USA, SUX',
  'Sioux Falls (SD), USA, FSD',
  'Sishen, South Africa, SIS',
  'Sitka (AK), USA, SIT',
  'Sivas, Turkey, VAS',
  'Siwa, Egypt, SEW',
  'Skagway (AK), USA, SGY',
  'Skardu, Pakistan, KDU',
  'Skiathos, Greece, JSI',
  'Skopje, Macedonia, SKP',
  'Skrydstrup, Denmark, SKS',
  'Skukuza, South Africa, SZK',
  'Sligo, Ireland, SXL',
  'Smithers, Canada, YYD',
  'Sodankylae, Finland, SOT',
  'Soenderborg, Denmark, SGD',
  'Soendre Stroemfjord, Greenland, SFJ',
  'Sofia - Vrazhdebna, Bulgaria, SOF',
  'Sogndal, Norway, SOG',
  'Southampton - Eastleigh, United Kingdom, SOU',
  'South Bend (IN), USA, SBN',
  'South Indian Lake, MB, Canada, XSI',
  'South Molle Island, Australia, SOI',
  'Southend (London), United Kingdom, SEN',
  'Split, Croatia (Hrvatska), SPU',
  'Spokane (WA), USA, GEG',
  'Springbok, South Africa, SBU',
  'Springfield (IL), USA, SPI',
  'Springfield (MO), USA, SGF',
  'Srinagar, India, SXR',
  'St. Augustin, PQ, Canada, YIF',
  'St. Croix, Virgin Islands (U.S.), STX',
  'St. Etienne, France, EBU',
  'St. George (UT), USA, SGU',
  'St. John\'s, Canada, YYT',
  'St. Kitts, St. Kitts and Nevis, SKB',
  'St. Louis (MO) Lambert, USA, STL',
  'St. Lucia Hewanorra, Saint Lucia, UVF',
  'St. Lucia Vigle, Saint Lucia, SLU',
  'St. Marteen, Netherlands Antilles, SXM',
  'St. Martin, St. Martin (Guadeloupe), SFG',
  'St. Petersburg (Leningrad) - Pulkovo, Russia, LED',
  'St. Pierre, NF, Canada, FSP',
  'St. Thomas, Virgin Islands (U.S.), STT',
  'St. Vincent, Saint Vincent and the Grenadines, SVD',
  'Stansted (London), United Kingdom, STN',
  'State College/Belefonte (PA), USA, SCE',
  'Stavanger, Norway, SVG',
  'Steamboat Springs (CO), USA, HDN',
  'Stettin, Poland, SZZ',
  'Stockholm Metropolitan Area, Sweden, STO',
  'Stockholm - Arlanda, Sweden, ARN',
  'Stockholm - Bromma, Sweden, BMA',
  'Stockton (CA), USA, SCK',
  'Stornway, United Kingdom, SYY',
  'Strasbourg, France, SXB',
  'Streaky Bay, Australia, KBY',
  'Stuttgart - Echterdingen, Germany, STR',
  'Sui, Pakistan, SUL',
  'Sukkur, Pakistan, SKZ',
  'Sumburgh (Shetland), United Kingdom, LSI',
  'Sun Valley (ID), USA, SUN',
  'Sundsvall, Sweden, SDL',
  'Sunshine Coast, Australia, MCY',
  'Surabaya - Juanda, Indonesia, SUB',
  'Surat, India, STV',
  'Suva, Fiji, SUV',
  'Swakopmund, Namibia, SWP',
  'Sydney, Australia, SYD',
  'Sylhet, Bangladesh, ZYL',
  'Syracuse (NY), USA, SYR',
  'Tabuk, Saudi Arabia, TUU',
  'Taif, Saudi Arabia, TIF',
  'Taipei - Chiang Kai Shek, Taiwan, TPE',
  'Taipei - Sung Shan, Taiwan, TAY',
  'Taiyuan, Shanxi, PR China, TYN',
  'Takamatsu, Japan, TAK',
  'Talkeetna (AK), USA, TKA',
  'Tallahassee (FL), USA, TLH',
  'Tallinn - Pirita Harbour, Estonia, QUF',
  'Tallinn - Ulemiste, Estonia, TLL',
  'Tampa (FL), USA, TPA',
  'Tampere, Finland, TMP',
  'Tampico - Gen. F. Javier Mina, Mexico, TAM',
  'Tamworth, Australia, TMW',
  'Tangier - Boukhalef, Morocco, TNG',
  'Taree, Australia, TRO',
  'Targovishte, Bulgaria, TGV',
  'Tashkent, Uzbekistan, TAS',
  'Tawau, Malaysia, TWU',
  'Tbilisi - Novo Alexeyevka, Georgia, TBS',
  'Te Anau, New Zealand, TEU',
  'Teesside, Durham Tees Valley, United Kingdom, MME',
  'Tegucigalpa, Honduras, TGU',
  'Tehran (Teheran) - Mehrabad, Iran, THR',
  'Tekirdag - Corlu, Turkey, TEQ',
  'Tel Aviv, Israel, TLV',
  'Telluride (CO), USA, TEX',
  'Temora, Australia, TEM',
  'Tenerife, Spain, TCI',
  'Tenerife - Sur Reina Sofia, Spain, TFS',
  'Tenerife - Norte Los Rodeos, Spain, TFN',
  'Tennant Creek, Australia, TCA',
  'Terceira, Portugal, TER',
  'Teresina, Brazil, THE',
  'Termez (Termes), Uzbekistan, TMZ',
  'Terrace, Canada, YXT',
  'Terre Haute (IN), USA, HUF',
  'Texarkana (AR), USA, TXK',
  'Thaba\'Nchu, South Africa, TCU',
  'The Pas, Canada, YQD',
  'Thessaloniki - Makedonia Apt., Greece, SKG',
  'Thief River Falls (MN), USA, TVF',
  'Thira, Greece, JTR',
  'Thiruvananthapuram, India, TRV',
  'Thisted, Denmark, TED',
  'Thompson, Canada, YTH',
  'Thorne Bay (AK), USA, KTB',
  'Thunder Bay, Canada, YQT',
  'Thursday Island, Australia, TIS',
  'Tianjin, China, TSN',
  'Tijuana - Rodriguez, Mexico, TIJ',
  'Tioman, Indonesia, TOD',
  'Tirana - Rinas, Albania, TIA',
  'Tiruchirapally, India, TRZ',
  'Tivat, Montenegro, TIV',
  'Tobago, Trinidad and Tobago, TAB',
  'Tokushima, Japan, TKS',
  'Tokyo, Japan, TYO',
  'Tokyo - Haneda, Japan, HND',
  'Tokyo - Narita, Japan, NRT',
  'Toledo (OH), USA, TOL',
  'Tom Price, Australia, TPR',
  'Toowoomba, Australia, TWB',
  'Toronto - Billy Bishop Toronto City Airport, Canada, YTZ',
  'Toronto - Toronto Pearson International Airport, Canada, YYZ',
  'Toronto, Canada, YTO',
  'Tortola, British Virgin Islands, TOV',
  'Touho, New Caledonia, TOU',
  'Toulouse, France, TLS',
  'Townsville, Australia, TSV',
  'Toyama, Japan, TOY',
  'Trabzon, Turkey, TZX',
  'Trapani, Italy, TPS',
  'Traverse City (MI), USA, TVC',
  'Treasure Cay, Bahamas, TCB',
  'Trenton/Princeton (NJ), USA, TTN',
  'Treviso, Italy, TSF',
  'Tri-Cities Regional (TN) /VA, USA, TRI',
  'Trieste, Italy, TRS',
  'Tripoli , Libya, TIP',
  'Tromsoe, Norway, TOS',
  'Trondheim, Norway, TRD',
  'Tsumeb, Namibia, TSB',
  'Tucson (AZ), USA, TUS',
  'Tulepo (MS), USA, TUP',
  'Tulsa (OK), USA, TUL',
  'Tunis - Carthage, Tunisia, TUN',
  'Turbat, Pakistan, TUK',
  'Turin, Italy, TRN',
  'Turku, Finland, TKU',
  'Tuscaloosa (AL), USA, TCL',
  'Tuxtla Gutierrez, Mexico, TGZ',
  'Twin Falls (ID), USA, TWF',
  'Tyler (TX), USA, TYR',
  'Ua Huka, French Polynesia, UAH',
  'Ua Pou, French Polynesia, UAP',
  'Ube, Japan, UBJ',
  'Uberaba, Brazil, UBA',
  'Uberlandia , Brazil, UDI',
  'Ubon Ratchathani, Thailand, UBP',
  'Udaipur, India, UDR',
  'Uden, Netherlands, UDE',
  'Udon Thani, Thailand, UTH',
  'Ufa, Russia, UFA',
  'Uherske Hradiste, Czech Republic, UHE',
  'Uige, Angola, UGO',
  'Ujung Pandang, Indonesia, UPG',
  'Ukhta, Russia, UCT',
  'Ukiah (CA), USA, UKI',
  'Ulaanbaatar, Mongolia, ULN',
  'Ulan-Ude, Russia, UUD',
  'Ulanhot, PR China, HLH',
  'Ulei, Vanuatu, ULB',
  'Ulsan, South Korea, USN',
  'Ulundi, South Africa, ULD',
  'Umea, Sweden, UME',
  'Umiujaq, Canada, YUD',
  'Umtata, South Africa, UTT',
  'Unalakleet (AK), USA, UNK',
  'Union Island, Saint Vincent and the Grenadines, UNI',
  'Unst (Shetland Island), United Kingdom, UNT',
  'Upala, Costa Rica, UPL',
  'Upernavik - Upernavik Heliport, Greenland, JUV',
  'Upington, South Africa, UTN',
  'Upolu Point (HI), USA, UPP',
  'Uranium City, Canada, YBE',
  'Urgench, Uzbekistan, UGC',
  'Uriman, Venezuela, URM',
  'Urmiehm (Orumieh), Iran, OMH',
  'Uruapan, Mexico, UPN',
  'Urubupunga, Brazil, URB',
  'Uruguaiana, Brazil, URG',
  'Urumqi, Xinjiang, PR China, URC',
  'Uruzgan, Afghanistan, URZ',
  'Ushuaia, Argentina, USH',
  'Utapao (Pattaya), Thailand, UTP',
  'Utica (NY), USA, UCA',
  'Utila, Honduras, UII',
  'Uummannaq, Greenland, UMD',
  'Uzhgorod, Ukraine, UDJ',
  'Vaasa, Finland, VAA',
  'Vaexjoe, Sweden, VXO',
  'Vail (CO), USA, EGE',
  'Val d\'Or, Canada, YVO',
  'Valdez (AK), USA, VDZ',
  'Valdosta (GA), USA, VLD',
  'Valencia, Spain, VLC',
  'Valencia, Venezuela, VLN',
  'Valladolid, Spain, VLL',
  'Valparaiso, Chile, VAP',
  'Valverde, Spain, VDE',
  'Van - Ferit Melen, Turkey, VAN',
  'Vancouver, Canada, YVR',
  'Varadero, Cuba, VRA',
  'Varanasi, India, VNS',
  'Varkaus, Finland, VRK',
  'Varna, Bulgaria, VAR',
  'Vasteras, Sweden, VST',
  'Velikiye Luki (Welikije Luki), Russia, VLU',
  'Venice - Marco Polo, Italy, VCE',
  'Veracruz, Mexico, VER',
  'Vernal (UT), USA, VEL',
  'Vero Beach/Ft. Pierce (FL), USA, VRB',
  'Verona (Brescia) Montichiari, Italy, VBS',
  'Verona, Italy, VRN',
  'Victoria, Canada, YYJ',
  'Victoria Falls, Zimbabwe, VFA',
  'Vidin, Bulgaria, VID',
  'Vientiane - Wattay, Lao PDR, VTE',
  'Vigo, Spain, VGO',
  'Villahermosa, Mexico, VSA',
  'Vilnius, Lithuania, VNO',
  'Virgin Gorda, Virgin Islands (British), VIJ',
  'Visalia (CA), USA, VIS',
  'Visby, Sweden, VBY',
  'Vitoria, Spain, VIT',
  'Vitoria, Brazil, VIX',
  'Vryheid, South Africa, VYD',
  'Wabush, Canada, YWK',
  'Waco (TX), USA, ACT',
  'Wagga, Australia, WGA',
  'Walla Walla (WA), USA, ALW',
  'Wallis, Wallis and Futuna Islands, WLS',
  'Walvis Bay, South Africa, WVB',
  'Warrnambool, Australia, WMB',
  'Warsaw - Frédéric Chopin, Poland, WAW',
  'Washington DC - Baltimore Washington International, USA, BWI',
  'Washington DC - Dulles International, USA, IAD',
  'Washington DC - Ronald Reagan National, USA, DCA',
  'Washington DC, USA, WAS',
  'Waterloo IA, USA, ALO',
  'Watertown (SD), USA, ATY',
  'Wausau/Stevens Point (WI), USA, CWA',
  'Weipa, Australia, WEI',
  'Welkom, South Africa, WEL',
  'Wellington, New Zealand, WLG',
  'Wenatchee (WA), USA, EAT',
  'West Palm Beach (FL), USA, PBI',
  'West Yellowstone (MT), USA, WYS',
  'Westerland, Germany, GWT',
  'Whakatane, New Zealand, WHK',
  'Whale Cove, NT, Canada, YXN',
  'Whangarei, New Zealand, WRE',
  'White Plains (NY), USA, HPN',
  'Whitehorse, Canada, YXY',
  'Whitsunday Resort, Australia, HAP',
  'Whyalla, Australia, WYA',
  'Wichita Falls (TX), USA, SPS',
  'Wichita (KS), USA, ICT',
  'Wick, United Kingdom, WIC',
  'Wickham, Australia, WHM',
  'Wien (Vienna) , Austria, VIE',
  'Wiesbaden, Air Base, Germany, WIE',
  'Wilkes Barre/Scranton (PA), USA, AVP',
  'Williamsport (PA), USA, IPT',
  'Williston (ND), USA, ISL',
  'Wilmington (NC), USA, ILM',
  'Wilna (Vilnius), Lithuania, VNO',
  'Wiluna, Australia, WUN',
  'Windhoek - Eros, Namibia, ERS',
  'Windhoek - Hosea Kutako International, Namibia, WDH',
  'Windsor Ontario, Canada, YQG',
  'Winnipeg International, Canada, YWG',
  'Wolf Point (MT), USA, OLF',
  'Wollongong, Australia, WOL',
  'Woomera, Australia, UMR',
  'Worcester (MA), USA, ORH',
  'Worland (WY), USA, WRL',
  'Wrangell (AK), USA, WRG',
  'Wuhan, Hubei, PR China, WUH',
  'Wyndham, Australia, WYN',
  'Xiamen, Fujian, PR China, XMN',
  'Xi\'an - Xianyang, Shaanxi, PR China, XIY',
  'Yakima (WA), USA, YKM',
  'Yakutat (AK), USA, YAK',
  'Yakutsk, Russia, YKS',
  'Yamagata, Junmachi, Japan, GAJ',
  'Yamoussoukro, Côte d\'Ivoire, ASK',
  'Yanbu, Saudi Arabia, YNB',
  'Yangon (Rangoon) - Mingaladon, Myanmar, RGN',
  'Yaounde, Cameroon, YAO',
  'Yellowknife, Canada, YZF',
  'Yekaterinburg, Russia, SVX',
  'Yichang, Hubei, PR China, YIH',
  'Yokohama, Japan, YOK',
  'Yuma (AZ), USA, YUM',
  'Zacatecas, Mexico, ZCL',
  'Zadar, Croatia (Hrvatska), ZAD',
  'Zagreb, Croatia (Hrvatska), ZAG',
  'Zakynthos, Greece, ZTH',
  'Zaragoza, Spain, ZAZ',
  'Zhob, Pakistan, PZH',
  'Zinder, Niger, ZND',
  'Zouerate, Mauritania, OUZ',
  'Zurich (Zürich) - Kloten, Switzerland, ZRH',  
]
  
  constructor (
    private fb:FormBuilder,
    private auth: AuthService,
    private airlineService: AirlineService,
    private customerService: CustomerService, 
    private bookingService: BookingsService,
    private dialog: MatDialog,
    private matDialogRef:MatDialogRef<BookairlineComponent>,
    private snackBar: MatSnackBar,
    @Inject(MAT_DIALOG_DATA) public data: any,
    private employeeService: EmployeeService, 
    private activityLogs:ActivitylogService,
  ) {
    
    if(data.row != null) {
      this.editState=true;
      console.log(data.row)
      this.flightDetails = data.row;
      this.customerCtrl.setValue(data.row.customerName);
      this.bookByCtrl.setValue(data.row.bookByName);
      if(data.row.isInternational == 1) {        
        this.internationalFlight = true;
        this.internationalToCtrl.setValue(data.row.to);
        this.internationalFromCtrl.setValue(data.row.from);
        if(data.row.flightNoConnecting != null) {
          this.connectingFlight = true;
          this.internationalConnectingToCtrl.setValue(data.row.connectingTo);
          this.internationalConnectingFromCtrl.setValue(data.row.connectingFrom);
        }
        if(data.row.flightNoConnecting == null) {
          this.connectingFlight = false;
        }
        if(data.row.flightNoReturn != null) {
          this.roundTrip = true;
          if(data.row.flightNoConnectingReturn != null) {
            this.connectingReturnFlight = true;
            this.internationalConnectingReturnToCtrl.setValue(data.row.connectingReturnTo);
            this.internationalConnectingReturnFromCtrl.setValue(data.row.connectingReturnFrom);
          }
        }
        else if(data.row.flightNoReturn == null) {
          this.roundTrip = false;
          this.connectingReturnFlight = false;
        }
      }
      else if(data.row.isInternational == 0) {
        this.internationalFlight = false;
        this.domesticToCtrl.setValue(data.row.to);
        this.domesticFromCtrl.setValue(data.row.from);
        if(data.row.flightNoConnecting != null) {
          this.connectingFlight = true;
          this.domesticConnectingToCtrl.setValue(data.row.connectingTo);
          this.domesticConnectingFromCtrl.setValue(data.row.connectingFrom);
        }
        if(data.row.flightNoConnecting == null) {
          this.connectingFlight = false;
        }
        if(data.row.flightNoReturn != null) {
          this.roundTrip = true;
          if(data.row.flightNoConnectingReturn != null) {
            this.connectingReturnFlight = true;
            this.domesticConnectingReturnToCtrl.setValue(data.row.connectingReturnTo);
            this.domesticConnectingReturnFromCtrl.setValue(data.row.connectingReturnFrom);
          }
        }
        else if(data.row.flightNoReturn == null) {
          this.roundTrip = false;
          this.connectingReturnFlight = false;
        }
      }      
    }
    else {
      this.editState=false;
    }
  }

  ngOnInit() {
    var HOST = location.origin.replace(/^http/, 'ws')
    this.ws = new WebSocket(HOST);
    console.log(this.internationalFlight);
    this.bookFlight = this.fb.group({
      guestName: [''],
      guestMobile: [''],
      guestEmail: [''],      
      internationalRadioGroup: [''],
      connectingRadioGroup: [''],
      roundTripRadioGroup: [''],
      roundTripConnectingRadioGroup: [''],
      internationalFrom: [''],
      internationalTo: [''],
      from: [''],
      to: [''],
      departureDate: [''],
      arrivalDate: [''],
      bookByName: [''],
      bookByNo: [''],
      bookByEmail: [''],
      price: [''],
      handlingCharges: [''],
      flightNo: [''],
      flightNoReturn: [''],
      flightNoConnecting: [''],
      flightNoConnectingReturn: [''],
    })

    this.bookFlight.patchValue({
      'guestName': this.flightDetails.guestName,
      'guestMobile': this.flightDetails.guestMobile,
      'guestEmail': this.flightDetails.guestEmail,      
      'departureDate': this.flightDetails.departureDate,
      'arrivalDate': this.flightDetails.arrivalDate,
      'bookByName': this.flightDetails.bookByName,
      'bookByNo': this.flightDetails.bookByNo,
      'bookByEmail': this.flightDetails.bookByEmail,
      'price': this.flightDetails.price,
      'handlingCharges': this.flightDetails.handlingCharges,
      'flightNo': this.flightDetails.flightNo,
    })

    if(this.internationalFlight == true) {
      this.bookFlight.patchValue({
        'internationalRadioGroup': 'international'
      })
    }
    if(this.internationalFlight == false) {
      this.bookFlight.patchValue({
        'internationalRadioGroup': 'domestic'
      })
    }

    if(this.connectingFlight == true) {
      this.bookFlight.patchValue({
        'connectingRadioGroup': 'yes',
        'flightNoConnecting': this.flightDetails.flightNoConnecting
      })
    }
    if(this.connectingFlight == false) {
      this.bookFlight.patchValue({
        'connectingRadioGroup': 'no'
      })
    }

    if(this.roundTrip == true) {
      this.bookFlight.patchValue({
        'roundTripRadioGroup': 'roundTrip',
        'flightNoReturn': this.flightDetails.flightNoReturn        
      })
      if(this.connectingReturnFlight == true) {
        this.bookFlight.patchValue({
          'roundTripConnectingRadioGroup': 'yes',
          'flightNoConnectingReturn': this.flightDetails.flightNoConnectingReturn
        })
      }
    }
    if(this.roundTrip == false) {
      this.bookFlight.patchValue({
        'roundTripRadioGroup': 'singleTrip',
        'roundTripConnectingRadioGroup': 'no',
      })
    }
    
    this.auth.user.subscribe(data => {
      this.user = data[0]
      console.log(this.user)
      if(this.user.type == 'employee') {
        var body = {
          userId: this.user.id
        }
        this.employeeService.getEmployeeForCustomer(body).subscribe(data => {
          this.employeeService.getEmployeeLimitCustomerForEmployee(data[0]).subscribe(data => {
            if(data.length != 0) {              
              this.customers=data;
              this.customer=this.customerCtrl.valueChanges
              .pipe(
                startWith(''),
                map(val=>this.filterCustomer(val))
              );
            }
            else {
              this.getCustomer();
            }
          })
        })
      }
      else {
        this.getCustomer();
      }
      this.domesticAirportsFrom = this.domesticFromCtrl.valueChanges
      .pipe(
        startWith(''),
        map(val => this.filterdomesticAirports(val))
      );
      this.domesticAirportsTo = this.domesticToCtrl.valueChanges
      .pipe(
        startWith(''),
        map(val => this.filterdomesticAirports(val))
      )
      this.internationalAirportFrom = this.internationalFromCtrl.valueChanges
      .pipe(
        startWith(''),
        map(val => this.filterinternationalAirports(val))
      )
      this.internationalAirportTo = this.internationalToCtrl.valueChanges
      .pipe(
        startWith(''),
        map(val => this.filterinternationalAirports(val))
      )
      this.domesticConnectingAirportFrom = this.domesticConnectingFromCtrl.valueChanges
      .pipe(
        startWith(''),
        map(val => this.filterdomesticAirports(val))
      );
      this.domesticConnectingAirportTo = this.domesticConnectingToCtrl.valueChanges
      .pipe(
        startWith(''),
        map(val => this.filterdomesticAirports(val))
      )
      this.internationalConnectingAirportFrom = this.internationalConnectingFromCtrl.valueChanges
      .pipe(
        startWith(''),
        map(val => this.filterinternationalAirports(val))
      )
      this.internationalConnectingAirportTo = this.internationalConnectingToCtrl.valueChanges
      .pipe(
        startWith(''),
        map(val => this.filterinternationalAirports(val))
      )
      this.domesticConnectingReturnAirportFrom = this.domesticConnectingReturnFromCtrl.valueChanges
      .pipe(
        startWith(''),
        map(val => this.filterdomesticAirports(val))
      );
      this.domesticConnectingReturnAirportTo = this.domesticConnectingReturnToCtrl.valueChanges
      .pipe(
        startWith(''),
        map(val => this.filterdomesticAirports(val))
      )
      this.internationalConnectingReturnAirportFrom = this.internationalConnectingReturnFromCtrl.valueChanges
      .pipe(
        startWith(''),
        map(val => this.filterinternationalAirports(val))
      )
      this.internationalConnectingReturnAirportTo = this.internationalConnectingReturnToCtrl.valueChanges
      .pipe(
        startWith(''),
        map(val => this.filterinternationalAirports(val))
      )      
    })
  }

  getCustomer() {
    this.customerService.getCustomers(this.user).subscribe(data=>{
      this.customers=data;
      this.customer=this.customerCtrl.valueChanges
      .pipe(
        startWith(''),
        map(val=>this.filterCustomer(val))
      );
    });
  }

  saveFlights() {
    if(this.internationalFlight == true) {
      this.flightDetails.isInternational = 1;
      this.flightDetails.from = this.internationalFromCtrl.value;
      this.flightDetails.to = this.internationalToCtrl.value;  
    }
    if(this.internationalFlight == false) {
      this.flightDetails.from = this.domesticFromCtrl.value;
      this.flightDetails.to = this.domesticToCtrl.value;
    }
    if(this.connectingFlight == true) {
      this.flightDetails.flightNoConnecting = this.bookFlight.get('flightNoConnecting').value;
      if(this.internationalFlight == true) {
        this.flightDetails.connectingFrom = this.internationalConnectingFromCtrl.value;
        this.flightDetails.connectingTo = this.internationalConnectingToCtrl.value;
      }
      else {
        this.flightDetails.connectingFrom = this.domesticConnectingFromCtrl.value;
        this.flightDetails.connectingTo = this.domesticConnectingToCtrl.value;
      }
    }
    if(this.roundTrip == true) {
      this.flightDetails.arrivalDate = this.bookFlight.get('arrivalDate').value;
      this.flightDetails.arrivalDate = moment(this.flightDetails.arrivalDate).format("YYYY-MM-DD");
      this.flightDetails.flightNoReturn = this.bookFlight.get('flightNoReturn').value;
      if(this.connectingReturnFlight == true) {
        this.flightDetails.flightNoConnectingReturn = this.bookFlight.get('flightNoConnectingReturn').value;
        if(this.internationalFlight == true) {
          this.flightDetails.connectingReturnFrom = this.internationalConnectingReturnFromCtrl.value;
          this.flightDetails.connectingReturnTo = this.internationalConnectingReturnToCtrl.value;
        }
        else {
          this.flightDetails.connectingReturnFrom = this.domesticConnectingReturnFromCtrl.value;
          this.flightDetails.connectingReturnTo = this.domesticConnectingReturnToCtrl.value;
        }
      }
    }
    this.flightDetails.guestName = this.bookFlight.get('guestName').value;
    this.flightDetails.guestMobile = this.bookFlight.get('guestMobile').value;
    this.flightDetails.guestEmail = this.bookFlight.get('guestEmail').value;
    this.flightDetails.departureDate = this.bookFlight.get('departureDate').value;
    this.flightDetails.departureDate=moment(this.flightDetails.departureDate).format("YYYY-MM-DD");
    //moment(this.flightDetails.departureDate).format("YYYY-MM-DD");    
    this.flightDetails.bookByName = this.bookByCtrl.value;
    this.flightDetails.bookByNo = this.bookFlight.get('bookByNo').value;
    this.flightDetails.bookByEmail = this.bookFlight.get('bookByEmail').value;
    this.flightDetails.price = this.bookFlight.get('price').value;
    this.flightDetails.handlingCharges = this.bookFlight.get('handlingCharges').value;
    this.flightDetails.flightNo = this.bookFlight.get('flightNo').value;
    this.flightDetails.ownerId = this.user.ownerId;
    this.flightDetails.status = 'Booked';

    this.airlineService.addFlights(this.flightDetails).subscribe(data => {
      this.activityLogs.addFlightLogs({
        flightBookingId:data.insertId,
        ownerId:this.user.ownerId,
        message:"Booking created on "+moment().format("DD-MM-YYYY")+" at "+new Date().toLocaleTimeString()+" by "+this.user.name
      }).subscribe()
    },err=>{},()=>{
      this.ws.send(this.user.ownerId+"airline");
      this.snackBar.open("Flight Booking Added", "X",{duration: 3000});
      this.dialog.closeAll();
    });
  }

  updateFlights() {
    if(this.internationalFlight == true) {
      this.flightDetails.isInternational = 1;
      this.flightDetails.from = this.internationalFromCtrl.value;
      this.flightDetails.to = this.internationalToCtrl.value;  
    }
    if(this.internationalFlight == false) {
      this.flightDetails.from = this.domesticFromCtrl.value;
      this.flightDetails.to = this.domesticToCtrl.value;
    }
    if(this.connectingFlight == true) {
      this.flightDetails.flightNoConnecting = this.bookFlight.get('flightNoConnecting').value;
      if(this.internationalFlight == true) {
        this.flightDetails.connectingFrom = this.internationalConnectingFromCtrl.value;
        this.flightDetails.connectingTo = this.internationalConnectingToCtrl.value;
      }
      else {
        this.flightDetails.connectingFrom = this.domesticConnectingFromCtrl.value;
        this.flightDetails.connectingTo = this.domesticConnectingToCtrl.value;
      }
    }
    if(this.roundTrip == true) {
      this.flightDetails.arrivalDate = this.bookFlight.get('arrivalDate').value;
      this.flightDetails.arrivalDate = moment(this.flightDetails.arrivalDate).format("YYYY-MM-DD");
      this.flightDetails.flightNoReturn = this.bookFlight.get('flightNoReturn').value;
      if(this.connectingReturnFlight == true) {
        this.flightDetails.flightNoConnectingReturn = this.bookFlight.get('flightNoConnectingReturn').value;
        if(this.internationalFlight == true) {
          this.flightDetails.connectingReturnFrom = this.internationalConnectingReturnFromCtrl.value;
          this.flightDetails.connectingReturnTo = this.internationalConnectingReturnToCtrl.value;
        }
        else {
          this.flightDetails.connectingReturnFrom = this.domesticConnectingReturnFromCtrl.value;
          this.flightDetails.connectingReturnTo = this.domesticConnectingReturnToCtrl.value;
        }
      }
    }
    this.flightDetails.guestName = this.bookFlight.get('guestName').value;
    this.flightDetails.guestMobile = this.bookFlight.get('guestMobile').value;
    this.flightDetails.guestEmail = this.bookFlight.get('guestEmail').value;
    this.flightDetails.departureDate = this.bookFlight.get('departureDate').value;
    this.flightDetails.departureDate=moment(this.flightDetails.departureDate).format("YYYY-MM-DD");
    //moment(this.flightDetails.departureDate).format("YYYY-MM-DD");    
    this.flightDetails.bookByName = this.bookByCtrl.value;
    this.flightDetails.bookByNo = this.bookFlight.get('bookByNo').value;
    this.flightDetails.bookByEmail = this.bookFlight.get('bookByEmail').value;
    this.flightDetails.price = this.bookFlight.get('price').value;
    this.flightDetails.handlingCharges = this.bookFlight.get('handlingCharges').value;
    this.flightDetails.flightNo = this.bookFlight.get('flightNo').value;
    this.flightDetails.ownerId = this.user.ownerId;
    this.flightDetails.status = 'Booked';

    this.airlineService.updateFlights(this.flightDetails).subscribe(data=>{},err=>{},()=>{
      this.ws.send(this.user.ownerId+"airline");
      this.snackBar.open("Flight Booking Updated", "X", {duration: 3000});
      this.dialog.closeAll();
    });
  }

  closeDialog() {
    this.dialog.closeAll();
  }

  international() {
    this.internationalFlight = true;
  }
  domestic() {
    this.internationalFlight = false;
  }

  roundtrip() {
    this.roundTrip = true
    console.log(this.roundTrip)
  }
  singletrip() {
    this.roundTrip = false
  }

  connectingFlights() {    
    this.connectingFlight = true;
  }
  notConnectingFlight() {
    this.connectingFlight = false;
  }

  connectingReturnFlights() {    
    this.connectingReturnFlight = true;
  }
  notConnectingReturnFlight() {
    this.connectingReturnFlight = false;
  }

  setCustomer(temp,event:any) {
    if(event.source.selected == true) {
      this.flightDetails.customerId = temp.id;
      this.flightDetails.customerName = temp.name;
    }

    var tempCust = {
      ownerId: this.user.ownerId,
      customerId: temp.id
    }

    this.bookingService.getRecurringBookedBy(tempCust).subscribe(data => {
      this.bookByArr = data;
      this.bookBy = this.bookByCtrl.valueChanges
      .pipe(
        startWith(''),
        map(val => this.filterBookBy(val))
      );
    })
  }
  setBookBy(option,event:any) {
    if(event.source.selected == true) {
      this.flightDetails.bookByName = option.name;      
      this.flightDetails.bookByNo = option.phoneNo;
      this.flightDetails.bookByEmail = option.emailId;
      this.bookFlight.patchValue({
        'bookByNo':this.flightDetails.bookByNo,
        'bookByEmail':this.flightDetails.bookByEmail
      })
    }
  }

  filterCustomer(val:string) {
    return this.customers.filter(option =>
      option.name.toLowerCase().includes(val.toLowerCase()))
  }
  filterBookBy(val:string) {
    return this.bookByArr.filter(option =>
      option.name.toLowerCase().includes(val.toLowerCase()))
  }
  filterdomesticAirports(val:string): string[] {
    return this.airports.filter(option =>
      option.toLowerCase().includes(val.toLowerCase()))
  }
  filterinternationalAirports(val:string): string[] {
    return this.internationalAirports.filter(option =>
      option.toLowerCase().includes(val.toLowerCase()))
  }

  flightDetails: FlightDetails = {
    ownerId: '',
    from: '',
    to: '',
    departureDate: '',    
    customerId:'',
    customerName:'',
    guestName: '',
    guestMobile: '',
    guestEmail: '',
    bookByName: '',
    bookByNo: '',
    bookByEmail: '',
    price: 0,
    handlingCharges: '',
    flightNo: '',
    arrivalDate: '',
    flightNoReturn: '',
    flightNoConnecting: '',
    flightNoConnectingReturn: '',
    isInternational: 0,
    status: '',
    connectingFrom: '',
    connectingTo: '',
  }

}

export interface FlightDetails {
  id?: string,
  ownerId?: string,
  from?: string,
  to?: string,
  departureDate?: string,  
  customerName?:string,
  customerId?:string,
  guestName?: string,
  guestMobile?: string,
  guestEmail?: string,
  bookByName?: string,
  bookByNo?: string,
  bookByEmail?: string,
  price?: number,
  handlingCharges?: string,
  flightNo?: string,
  arrivalDate?: string,
  flightNoReturn?: string,
  flightNoConnecting?: string,
  flightNoConnectingReturn?: string,
  isInternational?: number,
  status?: string,
  connectingFrom?: string,
  connectingTo?: string,
  connectingReturnFrom?: string,
  connectingReturnTo?: string,
  ticket?: string,
  returnTicket?: string
}
