export class Vehicle {
  id?: string;
  modelname?: string;
  number?: string;
  vcolor?: string;
  fuelType?:string;
  seating?: string;
  branches?: string;
  companyName?: string;
  policyNumber?: string;
  issueDate?:string;
  dueDate?:string;
  premiumAmount?: string;
  coverAmount?: string;
  chassisNumber?: string;
  engineNumber?: string;
  regName?: string;
  regDate?: string;
  RTOAddress?: string;
  taxEfficiency?: string;
  expiryDateRTO?: string;
  authorizationNumber?: string;
  expiryDateAuth?:string;
  PUCNumber?: string;
  expiryDatePUC?:string;
  EMIAmount?: string;
  startDate?:string;
  endDate?:string;
  bankName?: string;
  EMIDay?:string;
  permitType?:string;
  permitExpiryDate?:string;
  fileName?:string;
  fileURL?:string;
  assignedDriver?:string;
  vehicleGroup?:string;
  assignedDriverId?:string;
  vehicleGroupId?:string;
  branchId?:string;
  ownerId?:string;
  fitnessNumber?: string;
  expiryDateFitness?: string;
  active?: boolean;
}
